/-
  STATUS: DISCOVERY
  AGENT: 10
  DIRECTION: Group A.2 — Mutual-information chain rule as the
              partition-level Shannon decomposition.
  SUMMARY:
    Reformulates the chain rule (R-SUB.7) as the "mutual information"
    identity in the information-bottleneck framing:

        knowledgeEntropy d  =  H_π(P, d)  +  E_{S ~ π}[H_S],

    where `E_{S ~ π}[H_S] := ∑_S π_S · condEntropy S d` is the expected
    within-subdomain entropy under the partition-mass weighting.  The
    identity is the same as Shannon's chain rule but framed so that
    `H_K - H_π = expected_conditional_entropy` is the *mutual
    information between the fine-grained activation index and the
    coarse-grained partition label* (under the partition's measurable
    structure).

    Two named results:

      • `entropy_chain_rule_dist`   — the chain identity.
      • `mutual_information_eq_HK_minus_Hpi`
                                    — definitional MI in this MIP gauge:
                                      `MI := H_K(d) - H_π(P, d) =
                                              ∑_S π_S · H_S ≥ 0`.

    The two are algebraically equivalent (linarith); we name them
    separately because the *framing* — "mutual information equals the
    coarse-graining gap" — is the information-theoretic content.

    Combined with Agent 10's `Hpi_le_knowledgeEntropy`, this file
    certifies the standard MIP-side reading:

        knowledgeEntropy(d)
            =  Hpi(P, d) [coarse-grained activity]
              +  expected within-partition residual.

    The within-partition residual is exactly the mutual information
    between `d` and the partition's σ-algebra; it is zero iff `d` is
    constant on each part (equivalence-class-uniform), which is Agent
    10's `Hpi_le_knowledgeEntropy` equality case (currently an
    OBSERVATION, see Group C.7).
-/
import MIP.Defs.Knowledge
import MIP.Discoveries.Agent3_PiEntropyBounds
import MIP.Discoveries.Agent10_PartitionEntropyReduction
import MIP.Results.RSUB7_HK_Chain

namespace MIP

namespace Agent10

open scoped BigOperators
open Real

variable {Ω : Type} [Fintype Ω] [DecidableEq Ω]

/-- **HEADLINE (Group A.2) — Shannon chain rule on a subdomain partition.**

For any normalised activation distribution `d` on `Ω` and any
`SubdomainPartition` `P`, the knowledge entropy decomposes as the
*partition entropy* plus the *expected within-subdomain entropy*:

    knowledgeEntropy d  =  H_π(P, d)  +  ∑_S π_S · condEntropy S d.

This is the standard information-theoretic chain rule applied to the
σ-algebra generated by `P`.  The within-partition term is the
*conditional entropy* `H(d | partition)`, weighted by the partition
mass. -/
theorem entropy_chain_rule_dist
    (d : ActivationDist Ω) (P : SubdomainPartition Ω) :
    knowledgeEntropy d
      = MIP.Agent3_PiEntropyBounds.Hpi d P
        + ∑ S ∈ P.parts,
            ((P.subdomainMass d S : NNReal) : ℝ) * condEntropy S d := by
  classical
  -- The proof structure mirrors `Hpi_le_knowledgeEntropy`: we reuse the
  -- per-part chain identity to get a clean equality, not just `≤`.
  set parts := P.parts
  set p : Ω → ℝ := fun ω => (d.p ω : ℝ) with hp_def
  -- Flatten the universe sum via the partition's biUnion = univ.
  have hflatten :
      ∑ ω, p ω * Real.log (p ω)
        = ∑ S ∈ parts, ∑ ω ∈ S, p ω * Real.log (p ω) := by
    have hcover : parts.biUnion id = Finset.univ := P.biUnion_eq_univ
    calc ∑ ω, p ω * Real.log (p ω)
        = ∑ ω ∈ (Finset.univ : Finset Ω), p ω * Real.log (p ω) := rfl
      _ = ∑ ω ∈ parts.biUnion id, p ω * Real.log (p ω) := by rw [hcover]
      _ = ∑ S ∈ parts, ∑ ω ∈ S, p ω * Real.log (p ω) :=
          Finset.sum_biUnion P.pairwiseDisjoint_id
  -- Per-part chain identity (same as in `Hpi_le_knowledgeEntropy`).
  have hpernn : ∀ S ∈ parts,
      ∑ ω ∈ S, p ω * Real.log (p ω)
        = (∑ ω ∈ S, p ω) * Real.log (∑ ω ∈ S, p ω)
          + ∑ ω ∈ S, p ω * Real.log (p ω / (∑ ω' ∈ S, p ω')) := by
    intro S _hS
    by_cases hπ : (∑ ω ∈ S, p ω) = 0
    · have h_all_zero : ∀ ω ∈ S, p ω = 0 := by
        have h_nonneg : ∀ ω ∈ S, 0 ≤ p ω := fun ω _ => (d.p ω).coe_nonneg
        intro ω hω
        exact (Finset.sum_eq_zero_iff_of_nonneg h_nonneg).mp hπ ω hω
      have hLHS : ∑ ω ∈ S, p ω * Real.log (p ω) = 0 := by
        apply Finset.sum_eq_zero
        intro ω hω; rw [h_all_zero ω hω]; ring
      have hRHS₁ : (∑ ω ∈ S, p ω) * Real.log (∑ ω ∈ S, p ω) = 0 := by
        rw [hπ]; ring
      have hRHS₂ : ∑ ω ∈ S, p ω * Real.log (p ω / (∑ ω' ∈ S, p ω')) = 0 := by
        apply Finset.sum_eq_zero
        intro ω hω; rw [h_all_zero ω hω]; ring
      rw [hLHS, hRHS₁, hRHS₂, add_zero]
    · have hπpos : 0 < (∑ ω ∈ S, p ω) := by
        have h_nn : (0 : ℝ) ≤ ∑ ω ∈ S, p ω :=
          Finset.sum_nonneg (fun ω _ => (d.p ω).coe_nonneg)
        exact lt_of_le_of_ne h_nn (Ne.symm hπ)
      exact MIP.HKChain.chain_atomic S p
        (fun ω _ => (d.p ω).coe_nonneg) hπpos
  -- Combine.
  have h_within :
      ∀ S ∈ parts,
        ∑ ω ∈ S, p ω * Real.log (p ω / (∑ ω' ∈ S, p ω'))
          = (∑ ω ∈ S, p ω) * (- condEntropy S d) := by
    intro S _hS
    by_cases hπ : (∑ ω ∈ S, p ω) = 0
    · have h_all_zero : ∀ ω ∈ S, p ω = 0 := by
        have h_nonneg : ∀ ω ∈ S, 0 ≤ p ω := fun ω _ => (d.p ω).coe_nonneg
        intro ω hω
        exact (Finset.sum_eq_zero_iff_of_nonneg h_nonneg).mp hπ ω hω
      have hLHS : ∑ ω ∈ S, p ω * Real.log (p ω / (∑ ω' ∈ S, p ω')) = 0 := by
        apply Finset.sum_eq_zero
        intro ω hω; rw [h_all_zero ω hω]; ring
      rw [hLHS, hπ]; ring
    · have hπpos : 0 < (∑ ω ∈ S, p ω) := by
        have h_nn : (0 : ℝ) ≤ ∑ ω ∈ S, p ω :=
          Finset.sum_nonneg (fun ω _ => (d.p ω).coe_nonneg)
        exact lt_of_le_of_ne h_nn (Ne.symm hπ)
      have hπne : (∑ ω ∈ S, p ω) ≠ 0 := ne_of_gt hπpos
      unfold condEntropy condProb
      have hper : ∀ ω ∈ S,
          p ω * Real.log (p ω / (∑ ω' ∈ S, p ω'))
            = (∑ ω' ∈ S, p ω') *
                ((p ω / (∑ ω' ∈ S, p ω')) * Real.log (p ω / (∑ ω' ∈ S, p ω'))) := by
        intro ω _
        field_simp
      rw [Finset.sum_congr rfl hper, ← Finset.mul_sum]
      ring
  have h_decomp :
      ∑ ω, p ω * Real.log (p ω)
        = (∑ S ∈ parts, (∑ ω ∈ S, p ω) * Real.log (∑ ω ∈ S, p ω))
          + ∑ S ∈ parts, (∑ ω ∈ S, p ω) * (- condEntropy S d) := by
    rw [hflatten, Finset.sum_congr rfl hpernn, Finset.sum_add_distrib,
        Finset.sum_congr rfl h_within]
  -- Re-express in terms of `knowledgeEntropy d`, `Hpi d P`, and the
  -- subdomain-mass cast.
  unfold knowledgeEntropy MIP.Agent3_PiEntropyBounds.Hpi
  have h_mass_eq : ∀ S ∈ parts,
      ((P.subdomainMass d S : NNReal) : ℝ) = ∑ ω ∈ S, p ω := by
    intro S _hS
    show ((∑ ω ∈ S, d.p ω : NNReal) : ℝ) = ∑ ω ∈ S, (d.p ω : ℝ)
    push_cast; rfl
  -- Rewrite the partition-entropy sum using the mass identity.
  -- Goal:
  --   -∑ ω, p ω · log p ω
  --     = -∑ S, π_S · log π_S  +  ∑ S, π_S · condEntropy S d.
  -- From h_decomp:
  --   ∑ ω, p ω · log p ω = ∑ S, π_S · log π_S - ∑ S, π_S · condEntropy S d,
  -- so the negation gives the desired identity.
  -- We rewrite the goal step by step.
  have h_sum_pi_log :
      ∑ S ∈ parts,
          ((P.subdomainMass d S : NNReal) : ℝ)
            * Real.log ((P.subdomainMass d S : NNReal) : ℝ)
        = ∑ S ∈ parts, (∑ ω ∈ S, p ω) * Real.log (∑ ω ∈ S, p ω) := by
    apply Finset.sum_congr rfl
    intro S hS
    rw [h_mass_eq S hS]
  have h_sum_pi_H :
      ∑ S ∈ parts,
          ((P.subdomainMass d S : NNReal) : ℝ) * condEntropy S d
        = ∑ S ∈ parts, (∑ ω ∈ S, p ω) * condEntropy S d := by
    apply Finset.sum_congr rfl
    intro S hS
    rw [h_mass_eq S hS]
  rw [h_sum_pi_log, h_sum_pi_H]
  -- Goal: -∑ ω, p ω · log p ω
  --        = -∑ S, (∑ ω ∈ S, p ω) · log (∑ ω ∈ S, p ω)
  --          + ∑ S, (∑ ω ∈ S, p ω) · condEntropy S d.
  rw [h_decomp]
  -- ∑ S, π_S · (-H_S) = -∑ S, π_S · H_S.
  have h_residual_neg :
      ∑ S ∈ parts, (∑ ω ∈ S, p ω) * (- condEntropy S d)
        = -∑ S ∈ parts, (∑ ω ∈ S, p ω) * condEntropy S d := by
    rw [← Finset.sum_neg_distrib]
    apply Finset.sum_congr rfl
    intro S _; ring
  rw [h_residual_neg]
  ring

/-- **Mutual information** between the fine-grained activation index and
the coarse-graining partition label.

`MI(d, P) := knowledgeEntropy d - H_π(P, d)`.

By the chain rule, this equals the *expected within-subdomain entropy*
`∑_S π_S · condEntropy S d`.  It is nonneg by `Hpi_le_knowledgeEntropy`
(Agent 10), and zero iff `d` is uniform within each part (Group C.7,
not formally proved here). -/
noncomputable def mutualInformation
    (d : ActivationDist Ω) (P : SubdomainPartition Ω) : ℝ :=
  knowledgeEntropy d - MIP.Agent3_PiEntropyBounds.Hpi d P

/-- **Mutual information identity.** In the present MIP gauge,

    MI(d, P)  =  knowledgeEntropy d  -  H_π(P, d)
              =  ∑_S π_S · condEntropy S d  ≥  0. -/
theorem mutualInformation_eq_expected_condEntropy
    (d : ActivationDist Ω) (P : SubdomainPartition Ω) :
    mutualInformation d P
      = ∑ S ∈ P.parts,
          ((P.subdomainMass d S : NNReal) : ℝ) * condEntropy S d := by
  unfold mutualInformation
  linarith [entropy_chain_rule_dist d P]

/-- **Mutual information is nonneg.**  Direct corollary of
`Hpi_le_knowledgeEntropy`. -/
theorem mutualInformation_nonneg
    (d : ActivationDist Ω) (P : SubdomainPartition Ω) :
    0 ≤ mutualInformation d P := by
  unfold mutualInformation
  linarith [Hpi_le_knowledgeEntropy d P]

end Agent10

end MIP
