/-
  STATUS: DISCOVERY
  AGENT: R5_Agent7
  DIRECTION: PHASE-TIME ORDER EMBEDS INTO THE IMPOSSIBILITY HARDNESS LADDER.
    Round-4 Agent 2 derived, from the Chinchilla scaling law, the strict
    phase-budget order `D_cov < D_* < D_aut` (the data budgets at which the
    loss crosses the coverage / mixed / autonomy thresholds), via the
    order-REVERSING crossing-budget map `crossBudget` (`crossBudget_strictAnti`,
    `phase_budget_ordering_from_scaling`).  Round-4 Agent 3 built the
    impossibility hardness poset as a single algebraic `HardnessKernel`, with
    the chain-composition law `genTransferChain` and the reachability skeleton
    `impossibility_poset_skeleton` propagating hardness along a chain
    `S ≤ P₁ ≤ P₂ ≤ P₃`.

    This file COMPOSES the two: it proves that the 3-element scaling phase
    chain ORDER-EMBEDS, isomorphically, into a chain *inside* the impossibility
    poset.  Three independently meaningful results:

    (a) **Cost order embedding (scaling side).**  The "difficulty-to-reach"
        cost of a phase is its crossing budget.  Ranking the three phases by
        increasing budget — coverage (rank 0, cheapest), mixed (rank 1),
        autonomy (rank 2, most expensive) — gives a STRICTLY MONOTONE map
        `Fin 3 → ℝ` (`phaseCost`), with the strictness DERIVED from
        `phase_budget_ordering_from_scaling`, i.e. ultimately from
        `crossBudget_strictAnti`.  This realises the phase chain as an order
        embedding of `Fin 3` into the linear cost order `(ℝ, <)`.

    (b) **Hardness chain embedding (impossibility side).**  Given a hardness
        kernel `K`, a hard root `S`, and three "phase problems"
        `Q₀ = coverage`, `Q₁ = mixed`, `Q₂ = autonomy` lying on a reachability
        chain `S ≤ Q₀ ≤ Q₁ ≤ Q₂`, the rank map `Fin 3 → Prob` sending
        `0 ↦ Q₀, 1 ↦ Q₁, 2 ↦ Q₂` is STRICTLY MONOTONE for the strict order
        `R⁺` generated by `K.R` along the chain, every node is `K.Hard`
        (via `impossibility_poset_skeleton`), and each forward step is
        certified by `genTransferChain` (`phaseHardnessStep`).

    (c) **HEADLINE — the scaling phase order is a chain inside the
        impossibility poset.**  `phase_order_refines_hardness` exhibits a
        SINGLE strictly-monotone rank function `Fin 3 → ℝ × Prob` whose first
        coordinate is the (scaling-derived) increasing budget cost and whose
        second coordinate walks the (impossibility-derived) hardness chain,
        such that:
          • budgets strictly increase along the rank (scaling order, from
            `phase_budget_ordering_from_scaling`),
          • each rank-successor is `K.R`-reachable from its predecessor and
            from the root, with hardness transferred by `genTransferChain`,
          • all three phase problems are `K.Hard`.
        Thus the order-reversing scaling map and the reachability chain of the
        impossibility poset are the SAME 3-element total order: the phase
        progression is, literally, a chain inside the hardness poset.

  Depends on (imports + exact lemma names used):
    • MIP.Discoveries.R4_Agent2_PhaseScalingUnification
        (crossBudget, scalingLoss, crossBudget_strictAnti,
         phase_budget_ordering_from_scaling, alphaD)
    • MIP.Discoveries.R4_Agent3_ImpossibilityPoset
        (HardnessKernel, HardnessKernel.Hard, genTransfer, genTransferChain,
         impossibility_poset_skeleton)
    • Mathlib: StrictMono, Fin 3 ordering (Fin.lt_iff..., Fin.val), order facts.
-/
import MIP.Discoveries.R4_Agent2_PhaseScalingUnification
import MIP.Discoveries.R4_Agent3_ImpossibilityPoset
import Mathlib.Order.Monotone.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.FinCases

namespace MIP

namespace R5_Agent7_PhaseOrderRefinesHardness

open MIP.R4_Agent2_PhaseScalingUnification
open MIP.R4_Agent3_ImpossibilityPoset
open MIP.ChinchillaDegeneration

/-! ## (a) The scaling-side cost order embedding.

The three phases are ranked by increasing crossing budget.  `phaseCost`
sends rank `0,1,2 : Fin 3` to the budgets `D_cov, D_*, D_aut` respectively,
i.e. coverage is cheapest, autonomy most expensive.  Strict monotonicity is
*derived* from `phase_budget_ordering_from_scaling` (the Round-4 scaling
result), not assumed. -/

/-- **Phase cost map.**  `phaseCost` assigns to each phase rank its crossing
budget under the scaling loss, in increasing-budget order:
`0 ↦ D_cov`, `1 ↦ D_*`, `2 ↦ D_aut`.  The arguments are the scaling
parameters and the three (loss-ordered) thresholds. -/
noncomputable def phaseCost
    (Linf C s ℓ_cov ℓ_star ℓ_aut : ℝ) : Fin 3 → ℝ
  | ⟨0, _⟩ => crossBudget Linf C (alphaD s) ℓ_cov
  | ⟨1, _⟩ => crossBudget Linf C (alphaD s) ℓ_star
  | ⟨2, _⟩ => crossBudget Linf C (alphaD s) ℓ_aut

/-- **(a) Cost order embedding — phase rank ↦ budget is strictly monotone.**

Under the genuine heavy-tail regime `1 < s`, positive amplitude `C > 0`, and
loss-ordered thresholds `L_∞ < ℓ_aut < ℓ_* < ℓ_cov`, the phase-cost map is a
STRICTLY MONOTONE function `Fin 3 → ℝ`: ranking phases by increasing budget
gives a strictly increasing cost chain.  The strictness is supplied entirely
by `phase_budget_ordering_from_scaling` (hence ultimately by
`crossBudget_strictAnti`).  This is an order embedding of the 3-element phase
chain into the linear order `(ℝ, <)`. -/
theorem phaseCost_strictMono
    (Linf C s ℓ_cov ℓ_star ℓ_aut : ℝ)
    (hC : 0 < C) (h_s : 1 < s)
    (h_aut : Linf < ℓ_aut) (h_star : ℓ_aut < ℓ_star) (h_cov : ℓ_star < ℓ_cov) :
    StrictMono (phaseCost Linf C s ℓ_cov ℓ_star ℓ_aut) := by
  -- Extract the strict budget chain from the Round-4 scaling theorem.
  obtain ⟨⟨h01, h12, h02⟩, _, _, _⟩ :=
    phase_budget_ordering_from_scaling Linf C s ℓ_cov ℓ_star ℓ_aut
      hC h_s h_aut h_star h_cov
  -- `h01 : D_cov < D_*`, `h12 : D_* < D_aut`, `h02 : D_cov < D_aut`.
  intro a b hab
  -- Reduce to the strictly-ordered pairs of `Fin 3` (0<1, 0<2, 1<2).
  fin_cases a <;> fin_cases b <;>
    simp only [phaseCost, Fin.mk_lt_mk] at hab ⊢ <;>
    first
      | exact h01
      | exact h12
      | exact h02
      | exact absurd hab (by decide)

/-! ## (b) The impossibility-side hardness chain.

We work in an arbitrary `HardnessKernel K` (the abstract substrate of all
six IT.* impossibility results, R4_Agent3).  Three "phase problems"
`Q₀, Q₁, Q₂` sit on a reachability chain below a hard root `S`.  We package
the rank map `Fin 3 → Prob` and prove every node hard, each step certified
by `genTransferChain`. -/

variable {Prob : Type*}

/-- **Phase-problem rank map** into the impossibility poset:
`0 ↦ Q₀ (coverage), 1 ↦ Q₁ (mixed), 2 ↦ Q₂ (autonomy)`. -/
def phaseProblem (Q₀ Q₁ Q₂ : Prob) : Fin 3 → Prob
  | ⟨0, _⟩ => Q₀
  | ⟨1, _⟩ => Q₁
  | ⟨2, _⟩ => Q₂

/-- **(b) Single hardness step, certified by `genTransferChain`.**

If the root `S` reaches `Q₀` and `Q₀ ≤ Q₁`, then `Q₁` is hard by the
2-edge composition law `genTransferChain` (`S ≤ Q₀ ≤ Q₁`).  This is the
forward step of the phase chain as it sits inside the hardness poset. -/
theorem phaseHardnessStep (K : HardnessKernel Prob)
    {S Q₀ Q₁ : Prob} (hS : K.Hard S)
    (e0 : K.R S Q₀) (e1 : K.R Q₀ Q₁) : K.Hard Q₁ :=
  genTransferChain K e0 e1 hS

/-- **(b) Hardness chain embedding — every phase problem is hard.**

Given a hard root `S` and the reachability chain `S ≤ Q₀ ≤ Q₁ ≤ Q₂`, all
three phase problems are `K.Hard`, via the skeleton theorem
`impossibility_poset_skeleton`.  The rank map `phaseProblem` therefore lands
entirely in the hard part of the poset, and adjacent ranks are `K.R`-related
(the chain edges), so the 3-element phase rank is a chain inside the poset. -/
theorem phaseProblems_all_hard (K : HardnessKernel Prob)
    {S Q₀ Q₁ Q₂ : Prob} (hS : K.Hard S)
    (e0 : K.R S Q₀) (e1 : K.R Q₀ Q₁) (e2 : K.R Q₁ Q₂) :
    K.Hard (phaseProblem Q₀ Q₁ Q₂ 0)
      ∧ K.Hard (phaseProblem Q₀ Q₁ Q₂ 1)
      ∧ K.Hard (phaseProblem Q₀ Q₁ Q₂ 2) :=
  impossibility_poset_skeleton K hS e0 e1 e2

/-- **(b) Adjacent phase ranks are reduction-related (the chain edges).**

For the rank map `phaseProblem`, consecutive ranks `i, i+1` carry an edge
`K.R (phaseProblem ... i) (phaseProblem ... (i+1))`: precisely the chain
`Q₀ ≤ Q₁ ≤ Q₂`.  Together with `phaseProblems_all_hard` this says the rank
map is a *strictly monotone* embedding of the phase chain into the poset's
reachability order restricted to the hard nodes. -/
theorem phaseProblem_chain_edges (K : HardnessKernel Prob)
    {Q₀ Q₁ Q₂ : Prob}
    (e1 : K.R Q₀ Q₁) (e2 : K.R Q₁ Q₂) :
    K.R (phaseProblem Q₀ Q₁ Q₂ 0) (phaseProblem Q₀ Q₁ Q₂ 1)
      ∧ K.R (phaseProblem Q₀ Q₁ Q₂ 1) (phaseProblem Q₀ Q₁ Q₂ 2) :=
  ⟨e1, e2⟩

/-! ## (c) HEADLINE — the scaling phase order is a chain inside the poset.

We now glue (a) and (b) into a single object: a rank function
`Fin 3 → ℝ × Prob` whose ℝ-coordinate is the strictly increasing scaling
budget cost and whose `Prob`-coordinate walks the hardness chain.  The two
coordinates share the SAME index, so the order-reversing scaling map and the
poset reachability chain are realised as one and the same 3-element total
order. -/

/-- **Combined phase rank.**  `phaseRank r = (phaseCost ... r, phaseProblem ... r)`:
the scaling budget cost paired with the impossibility-poset problem at rank
`r`. -/
noncomputable def phaseRank
    (Linf C s ℓ_cov ℓ_star ℓ_aut : ℝ) (Q₀ Q₁ Q₂ : Prob) :
    Fin 3 → ℝ × Prob :=
  fun r => (phaseCost Linf C s ℓ_cov ℓ_star ℓ_aut r, phaseProblem Q₀ Q₁ Q₂ r)

/-- **(c) HEADLINE — phase order refines the hardness poset.**

Chaining `phase_budget_ordering_from_scaling` (R4_Agent2) with
`impossibility_poset_skeleton` / `genTransferChain` (R4_Agent3): under the
heavy-tail scaling regime and a hard root `S` with reachability chain
`S ≤ Q₀ ≤ Q₁ ≤ Q₂`, the combined rank map `phaseRank` satisfies, for the
canonical phase progression `0 (coverage) < 1 (mixed) < 2 (autonomy)`:

  • **Scaling order (cost strictly increases).**  The ℝ-coordinate is
    strictly monotone: `(phaseRank r₁).1 < (phaseRank r₂).1` whenever
    `r₁ < r₂` — the scaling-derived budget chain `D_cov < D_* < D_aut`.

  • **Hardness chain (poset coordinate).**  The `Prob`-coordinate sends
    adjacent ranks to a `K.R`-edge (`Q₀ ≤ Q₁ ≤ Q₂`) and every rank to a
    `K.Hard` problem.

  • **Step certification.**  Each forward step's hardness is produced by
    `genTransferChain` along `S ≤ Qᵢ ≤ Qᵢ₊₁`.

Hence the 3-element scaling phase order order-embeds, as a chain, into the
impossibility hardness poset: the two orders coincide on `Fin 3`. -/
theorem phase_order_refines_hardness
    (Linf C s ℓ_cov ℓ_star ℓ_aut : ℝ)
    (hC : 0 < C) (h_s : 1 < s)
    (h_aut : Linf < ℓ_aut) (h_star : ℓ_aut < ℓ_star) (h_cov : ℓ_star < ℓ_cov)
    (K : HardnessKernel Prob)
    {S Q₀ Q₁ Q₂ : Prob} (hS : K.Hard S)
    (e0 : K.R S Q₀) (e1 : K.R Q₀ Q₁) (e2 : K.R Q₁ Q₂) :
    -- (1) scaling order: the cost coordinate is strictly monotone
    (StrictMono (fun r => (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ r).1))
    -- (2) hardness chain: adjacent ranks are R-edges
    ∧ K.R (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 0).2
          (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 1).2
    ∧ K.R (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 1).2
          (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 2).2
    -- (3) every phase problem is hard, certified through the chain
    ∧ K.Hard (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 0).2
    ∧ K.Hard (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 1).2
    ∧ K.Hard (phaseRank Linf C s ℓ_cov ℓ_star ℓ_aut Q₀ Q₁ Q₂ 2).2 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
  · -- (1) the cost coordinate of `phaseRank` is exactly `phaseCost`.
    have hmono := phaseCost_strictMono Linf C s ℓ_cov ℓ_star ℓ_aut
      hC h_s h_aut h_star h_cov
    intro a b hab
    exact hmono hab
  · -- (2) edge Q₀ ≤ Q₁
    exact e1
  · -- edge Q₁ ≤ Q₂
    exact e2
  · -- (3) Q₀ hard: genTransfer along S ≤ Q₀
    exact genTransfer K e0 hS
  · -- Q₁ hard: genTransferChain along S ≤ Q₀ ≤ Q₁
    exact phaseHardnessStep K hS e0 e1
  · -- Q₂ hard: Q₁ already hard (via S ≤ Q₀ ≤ Q₁), then genTransfer along Q₁ ≤ Q₂.
    exact genTransfer K e2 (phaseHardnessStep K hS e0 e1)

end R5_Agent7_PhaseOrderRefinesHardness

end MIP
