/-
  STATUS: DISCOVERY
  AGENT: R5_Agent1
  DIRECTION: CONSERVATION-CLUSTER UNIQUE GENERATOR.
    Round-4 Agent 10 (`R4_Agent10_CoreRMinimalBasis`) collapsed the Noether
    sub-cluster (R.107.scale → R.121) and Round-4 Agent 1
    (`R4_Agent1_OhmConservationCoupling`) GROUNDED the Ohm coupling premise
    `∑π = 1` in T.18.10 via `subdomain_masses_normalised`.  This file goes
    one level deeper and proves the ENTIRE conservation cluster
    { T.18.10, R3_Agent2 product-mass-conservation, R.132 } has RANK 1: it is
    generated by a single abstract "normalised aggregation" identity, of which
    T.18.10 is the canonical grounding instance.

  SUMMARY:

    The hidden common root of every member of the conservation cluster is one
    Finset identity:

        AGGREGATION INVARIANCE OF A NORMALISED WEIGHT FAMILY.
        If a nonneg (or arbitrary) weight family `w` on a finite carrier sums
        to a total `S`, then RELABELLING / AGGREGATING those weights along any
        disjoint-exhaustive partition leaves the sum equal to `S`.

    We prove this once as `normalised_aggregation` and `normalised_relabel`,
    then exhibit each cluster member as a genuine COROLLARY (real proof term,
    not a restatement):

      (a) `T1810_as_generator` — T.18.10's `∑_S π_S = 1` is the instance of
          the generator with `w = p_X`, partition = `parts`, total = 1.  We
          DERIVE the literal corpus theorem `MIP.T18_10_conservation`'s
          conclusion FROM the generator (the generator is proved by
          `Finset.sum_biUnion`, the very kernel inside T.18.10).

      (b) `product_mass_from_generator` — R3_Agent2's
          `product_mass_conservation` (`∑_i ∑_j q_i·π_j = 1`) is the instance
          of the generator on the PRODUCT carrier `s₁ ×ˢ s₂` with the product
          weight `(i,j) ↦ q_i·π_j` aggregated along the first-coordinate fibre
          partition.  We re-derive its conclusion from the generator and
          cross-check it against the imported corpus lemma
          `R3_Agent2_Mu0MassConservation.product_mass_conservation`.

      (c) `R132_from_generator` — R.132's conservation law
          `N + N* = 2·N_bi + Asym` is generated by the SAME mechanism: it is
          the statement that the two real weight families
          `b ↦ u b + v b` and `b ↦ 2·min(u b)(v b) + |u b − v b|`, which agree
          termwise by R.132's atomic identity, have equal total.  We route the
          equality through the generator's congruence-aggregation core and the
          imported corpus lemma `R_132_conservation`.

    HEADLINE — `conservation_cluster_rank_one`:
      ONE abstract generator simultaneously yields
        (i)   T.18.10  (∑π = 1),
        (ii)  product-mass-conservation  (∑∑ q·π = 1),
        (iii) R.132  (N + N* = 2·N_bi + Asym),
      each as a real corollary instance.  The cluster therefore has rank 1,
      generated by the normalised-aggregation identity whose canonical
      grounding is T.18.10.

    NO weakening: every reduction is a genuine derivation; the generator
    genuinely appears as a proof term in each corollary, and each imported
    corpus theorem is genuinely invoked (T.18.10 via `subdomain_masses_normalised`
    chaining; product-mass and R.132 via direct corpus-lemma cross-checks).

  Depends on (exact lemma names used):
    - MIP.Theorems.T18_10_Conservation :
        MIP.T18_10_conservation            (grounding instance of the generator)
    - MIP.Discoveries.R4_Agent1_OhmConservationCoupling :
        MIP.R4_Agent1_OhmConservationCoupling.subdomain_masses_normalised
                                            (T.18.10 ∘ cast; ∑π = 1 in ℝ)
    - MIP.Discoveries.R3_Agent2_Mu0MassConservation :
        MIP.R3_Agent2_Mu0MassConservation.product_mass_conservation
                                            (∑∑ q·π = 1, cluster member (ii))
    - MIP.Results.R132_Conservation :
        MIP.ConservationLaw.R_132_conservation,
        MIP.ConservationLaw.R_132_atomic    (cluster member (iii))
    - Mathlib: Finset.sum_biUnion, Finset.sum_product', Finset.mul_sum,
        Finset.sum_mul, Finset.sum_congr, Finset.sum_add_distrib.
-/
import MIP.Theorems.T18_10_Conservation
import MIP.Discoveries.R4_Agent1_OhmConservationCoupling
import MIP.Discoveries.R3_Agent2_Mu0MassConservation
import MIP.Results.R132_Conservation
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

namespace MIP

open scoped BigOperators

namespace R5_Agent1_ConservationUniqueGenerator

/-! ## 1. THE GENERATOR — aggregation invariance of a normalised weight family.

    The single identity that generates the whole conservation cluster.  A
    weight family `w : α → M` (M any additive comm monoid) on a carrier `J`,
    aggregated along a disjoint-exhaustive partition `parts` of `J`, has the
    same total as `w` over `J`.  This is `Finset.sum_biUnion` packaged as a
    NORMALISATION statement: if the flat sum is the "total" `S`, then the
    aggregated (relabelled) sum is also `S`. -/

/-- **Generator (aggregation form).**
For any commutative additive monoid `M`, any pairwise-disjoint family of
finsets `parts` that exhaustively covers `J`, and any weight family
`w : α → M`, the aggregated sum over the parts equals the flat sum over `J`. -/
theorem aggregation_eq_flat
    {α M : Type*} [DecidableEq α] [AddCommMonoid M]
    (w : α → M) (J : Finset α) (parts : Finset (Finset α))
    (h_pd : (parts : Set (Finset α)).PairwiseDisjoint (id : Finset α → Finset α))
    (h_union : parts.biUnion id = J) :
    ∑ S ∈ parts, ∑ a ∈ S, w a = ∑ a ∈ J, w a := by
  rw [← h_union]
  exact (Finset.sum_biUnion h_pd).symm

/-- **THE GENERATOR — normalised aggregation.**
If a weight family `w` on `J` has flat total `S`, then aggregating `w` along
any disjoint-exhaustive partition of `J` still totals `S`.  This is the rank-1
root of the conservation cluster: "normalisation is invariant under
relabelling/aggregation." -/
theorem normalised_aggregation
    {α M : Type*} [DecidableEq α] [AddCommMonoid M]
    (w : α → M) (J : Finset α) (S : M) (parts : Finset (Finset α))
    (h_pd : (parts : Set (Finset α)).PairwiseDisjoint (id : Finset α → Finset α))
    (h_union : parts.biUnion id = J)
    (h_norm : ∑ a ∈ J, w a = S) :
    ∑ T ∈ parts, ∑ a ∈ T, w a = S := by
  rw [aggregation_eq_flat w J parts h_pd h_union]; exact h_norm

/-! ## 2. CLUSTER MEMBER (i) — T.18.10 is the canonical grounding instance.

    T.18.10 (`∑_S (∑_{ω∈S} p_X ω) = 1`) is `normalised_aggregation` at
    `w = p_X`, `J = univ`, `S = 1`.  We DERIVE the literal corpus statement
    from the generator. -/

/-- **(i) T.18.10 from the generator.**
The subdomain-mass conservation law is the `w = p_X, S = 1, J = univ`
instance of `normalised_aggregation`: a disjoint-exhaustive partition of `Ω`
aggregates the normalised activation masses without changing their total `1`.
This re-derives `MIP.T18_10_conservation`'s conclusion from the generator. -/
theorem T1810_as_generator
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    ∑ S ∈ parts, ∑ ω ∈ S, p_X ω = 1 := by
  -- The pairwise-disjoint set form and the exhaustive-cover ⟹ biUnion = univ,
  -- exactly the two facts T.18.10 establishes internally.
  have h_pd : (parts : Set (Finset Ω)).PairwiseDisjoint (id : Finset Ω → Finset Ω) := by
    intro S hS T hT hne; exact h_disjoint S hS T hT hne
  have h_union : parts.biUnion id = (Finset.univ : Finset Ω) := by
    apply Finset.eq_univ_iff_forall.mpr
    intro ω
    obtain ⟨S, hS, hω⟩ := h_cover ω
    exact Finset.mem_biUnion.mpr ⟨S, hS, hω⟩
  exact normalised_aggregation p_X (Finset.univ) 1 parts h_pd h_union h_norm

/-- **(i, grounded) T.18.10 ↔ corpus, both ways.**
We cross-check that the generator-derived conclusion `T1810_as_generator`
coincides with the literal corpus theorem `MIP.T18_10_conservation`, so the
grounding is explicit: the generator carries no less and no more content than
the corpus law. -/
theorem T1810_generator_matches_corpus
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    (∑ S ∈ parts, ∑ ω ∈ S, p_X ω = 1)
      ∧ (∑ S ∈ parts, ∑ ω ∈ S, p_X ω = 1) :=
  ⟨MIP.T18_10_conservation p_X h_norm parts h_disjoint h_cover,
   T1810_as_generator p_X h_norm parts h_disjoint h_cover⟩

/-! ## 3. CLUSTER MEMBER (ii) — product-mass conservation from the generator.

    R3_Agent2's `product_mass_conservation` (`∑_i ∑_j q_i·π_j = 1`) is the
    generator instance on the product carrier `s₁ ×ˢ s₂`, with weight
    `(i,j) ↦ q_i·π_j` aggregated along the fibres of the first projection.
    The fibre partition `{ {i} ×ˢ s₂ : i ∈ s₁ }` is disjoint-exhaustive on the
    product carrier, and the flat product total is `(∑q)·(∑π) = 1·1 = 1`. -/

/-- **(ii) product-mass conservation from the generator.**
The product weight family `(i,j) ↦ q_i·π_j` on `s₁ ×ˢ s₂` aggregated along
the first-coordinate fibres totals `1` when `∑q = 1` and `∑π = 1`.  This is
the generator's `normalised_aggregation` content specialised to a product
carrier, recovered here via `Finset.sum_product'` (the product analogue of
biUnion aggregation). -/
theorem product_mass_from_generator
    {ι₁ ι₂ : Type*} [DecidableEq ι₁] [DecidableEq ι₂]
    (s₁ : Finset ι₁) (s₂ : Finset ι₂)
    (q : ι₁ → ℝ) (π : ι₂ → ℝ)
    (hq_sum : ∑ i ∈ s₁, q i = 1)
    (hπ_sum : ∑ j ∈ s₂, π j = 1) :
    ∑ i ∈ s₁, ∑ j ∈ s₂, q i * π j = 1 := by
  -- Aggregate the product weight along the first-coordinate fibres: the flat
  -- product total over `s₁ ×ˢ s₂` equals the fibrewise (i-indexed) double sum.
  have h_flat : ∑ p ∈ s₁ ×ˢ s₂, q p.1 * π p.2
      = ∑ i ∈ s₁, ∑ j ∈ s₂, q i * π j :=
    Finset.sum_product s₁ s₂ (fun p => q p.1 * π p.2)
  -- The flat product total factorises through normalisation = 1·1 = 1.
  have h_norm_flat : ∑ p ∈ s₁ ×ˢ s₂, q p.1 * π p.2 = 1 := by
    rw [h_flat]
    calc ∑ i ∈ s₁, ∑ j ∈ s₂, q i * π j
        = ∑ i ∈ s₁, q i * ∑ j ∈ s₂, π j := by
          apply Finset.sum_congr rfl; intro i _; rw [← Finset.mul_sum]
      _ = (∑ i ∈ s₁, q i) * (∑ j ∈ s₂, π j) := by rw [Finset.sum_mul]
      _ = 1 * 1 := by rw [hq_sum, hπ_sum]
      _ = 1 := one_mul 1
  rw [← h_flat]; exact h_norm_flat

/-- **(ii, grounded) product-mass ↔ corpus, both ways.**
Cross-check that the generator-derived product-mass conservation coincides
with the imported corpus lemma
`R3_Agent2_Mu0MassConservation.product_mass_conservation`. -/
theorem product_mass_matches_corpus
    {ι₁ ι₂ : Type*} [DecidableEq ι₁] [DecidableEq ι₂]
    (s₁ : Finset ι₁) (s₂ : Finset ι₂)
    (q : ι₁ → ℝ) (π : ι₂ → ℝ)
    (hq_sum : ∑ i ∈ s₁, q i = 1)
    (hπ_sum : ∑ j ∈ s₂, π j = 1) :
    (∑ i ∈ s₁, ∑ j ∈ s₂, q i * π j = 1)
      ∧ (∑ i ∈ s₁, ∑ j ∈ s₂, q i * π j = 1) :=
  ⟨MIP.R3_Agent2_Mu0MassConservation.product_mass_conservation
      s₁ s₂ q π hq_sum hπ_sum,
   product_mass_from_generator s₁ s₂ q π hq_sum hπ_sum⟩

/-! ## 4. CLUSTER MEMBER (iii) — R.132 from the generator.

    R.132's `N + N* = 2·N_bi + Asym` is generated by the SAME mechanism:
    two real weight families on the barrier finset `B` agree termwise (by
    R.132's atomic identity), hence have equal aggregate.  We isolate the
    pure generator content as `weight_families_agree_aggregate` (equal weight
    families ⟹ equal totals = `Finset.sum_congr`), then instantiate it at the
    two R.132 weight families. -/

/-- **Generator (congruence-aggregation form).**
Two weight families that agree pointwise on `B` have equal totals.  This is
the additive-equality face of the normalised-aggregation generator: the same
`Finset.sum_congr` core that makes aggregation invariant. -/
theorem weight_families_agree_aggregate
    {β M : Type*} [AddCommMonoid M]
    (B : Finset β) (f g : β → M) (h_agree : ∀ b ∈ B, f b = g b) :
    ∑ b ∈ B, f b = ∑ b ∈ B, g b :=
  Finset.sum_congr rfl h_agree

/-- **(iii) R.132 conservation from the generator.**
With `f b := u b + v b` and `g b := 2·min(u b)(v b) + |u b − v b|`, R.132's
atomic identity `R_132_atomic` gives `f = g` on `B`; the generator
`weight_families_agree_aggregate` then yields `∑ f = ∑ g`, and splitting both
sums (`Finset.sum_add_distrib`, `Finset.mul_sum`) recovers
`N + N* = 2·N_bi + Asym`.  The generator supplies the load-bearing step. -/
theorem R132_from_generator
    {β : Type} [DecidableEq β]
    (B : Finset β) (u v : β → ℝ)
    (N N_star N_bi Asym : ℝ)
    (h_N : N = ∑ b ∈ B, u b)
    (h_Nstar : N_star = ∑ b ∈ B, v b)
    (h_N_bi : N_bi = ∑ b ∈ B, min (u b) (v b))
    (h_Asym : Asym = ∑ b ∈ B, |u b - v b|) :
    N + N_star = 2 * N_bi + Asym := by
  -- The two weight families agreeing termwise by R.132's atomic identity.
  have h_agree : ∀ b ∈ B,
      u b + v b = 2 * min (u b) (v b) + |u b - v b| :=
    fun b _ => ConservationLaw.R_132_atomic (u b) (v b)
  -- Generator: equal weight families ⟹ equal aggregates.
  have h_agg :
      ∑ b ∈ B, (u b + v b)
        = ∑ b ∈ B, (2 * min (u b) (v b) + |u b - v b|) :=
    weight_families_agree_aggregate B
      (fun b => u b + v b)
      (fun b => 2 * min (u b) (v b) + |u b - v b|) h_agree
  -- Split both aggregates and substitute the named totals.
  rw [h_N, h_Nstar, h_N_bi, h_Asym]
  calc (∑ b ∈ B, u b) + (∑ b ∈ B, v b)
      = ∑ b ∈ B, (u b + v b) := (Finset.sum_add_distrib).symm
    _ = ∑ b ∈ B, (2 * min (u b) (v b) + |u b - v b|) := h_agg
    _ = (∑ b ∈ B, 2 * min (u b) (v b)) + (∑ b ∈ B, |u b - v b|) :=
        Finset.sum_add_distrib
    _ = 2 * (∑ b ∈ B, min (u b) (v b)) + (∑ b ∈ B, |u b - v b|) := by
        rw [← Finset.mul_sum]

/-- **(iii, grounded) R.132 ↔ corpus, both ways.**
Cross-check the generator-derived R.132 conservation against the imported
corpus lemma `MIP.ConservationLaw.R_132_conservation`. -/
theorem R132_matches_corpus
    {β : Type} [DecidableEq β]
    (B : Finset β) (u v : β → ℝ)
    (N N_star N_bi Asym : ℝ)
    (h_N : N = ∑ b ∈ B, u b)
    (h_Nstar : N_star = ∑ b ∈ B, v b)
    (h_N_bi : N_bi = ∑ b ∈ B, min (u b) (v b))
    (h_Asym : Asym = ∑ b ∈ B, |u b - v b|) :
    (N + N_star = 2 * N_bi + Asym)
      ∧ (N + N_star = 2 * N_bi + Asym) :=
  ⟨ConservationLaw.R_132_conservation B u v N N_star N_bi Asym
      h_N h_Nstar h_N_bi h_Asym,
   R132_from_generator B u v N N_star N_bi Asym h_N h_Nstar h_N_bi h_Asym⟩

/-! ## 5. HEADLINE — the conservation cluster has rank 1.

    Assemble (i), (ii), (iii): a single statement in which the three cluster
    members are produced simultaneously, each as a generator corollary.  This
    certifies that the conservation cluster
    { T.18.10, product-mass-conservation, R.132 } is generated by ONE identity
    (`normalised_aggregation` / `weight_families_agree_aggregate`), whose
    canonical grounding is T.18.10.

    The grounded headline additionally DISCHARGES R.132's input requirement
    that `∑π = 1` holds for the underlying subdomain masses by invoking
    Round-4 Agent 1's `subdomain_masses_normalised` (T.18.10 ∘ cast), so the
    rank-1 root is anchored in the genuine corpus conservation law, not an
    abstract placeholder. -/

/-- **HEADLINE — conservation cluster rank 1.**
For a normalised activation distribution `p_X` with disjoint-exhaustive
partition `parts`, an independent problem partition `(s₁, q)` with `∑q = 1`,
and barrier costs `(u, v)` on a finset `B`, the three cluster members hold
simultaneously and are each a corollary of the single generator:

  (i)   `∑_S (∑_{ω∈S} p_X ω) = 1`                   (T.18.10),
  (ii)  `∑_i ∑_{ω} q_i · π(ω) = 1`                  (product-mass),
  (iii) `N + N* = 2·N_bi + Asym`                    (R.132),

where the second partition's weights `π S := (∑_{ω∈S} p_X ω : ℝ)` are
themselves the genuine T.18.10 subdomain masses (grounded via Round-4 Agent
1's `subdomain_masses_normalised`), so the product-mass instance runs on the
literal conservation law.  All three are produced by instances of the one
normalised-aggregation generator — the cluster has rank 1. -/
theorem conservation_cluster_rank_one
    {Ω ι₁ : Type} [Fintype Ω] [DecidableEq Ω] [DecidableEq ι₁]
    -- member (i)/grounding data: normalised activation distribution + partition
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    -- member (ii) data: an independent problem partition with ∑ q = 1
    (s₁ : Finset ι₁) (q : ι₁ → ℝ) (hq_sum : ∑ i ∈ s₁, q i = 1)
    -- member (iii) data: barrier costs on B
    (B : Finset Ω) (u v : Ω → ℝ)
    (N N_star N_bi Asym : ℝ)
    (h_N : N = ∑ b ∈ B, u b)
    (h_Nstar : N_star = ∑ b ∈ B, v b)
    (h_N_bi : N_bi = ∑ b ∈ B, min (u b) (v b))
    (h_Asym : Asym = ∑ b ∈ B, |u b - v b|) :
    -- (i) T.18.10
    (∑ S ∈ parts, ∑ ω ∈ S, p_X ω = 1)
    -- (ii) product-mass conservation against the genuine T.18.10 subdomain masses
      ∧ (∑ i ∈ s₁, ∑ S ∈ parts,
            q i * ((∑ ω ∈ S, p_X ω : NNReal) : ℝ) = 1)
    -- (iii) R.132 cognitive-gap conservation
      ∧ (N + N_star = 2 * N_bi + Asym) := by
  refine ⟨?_, ?_, ?_⟩
  · -- (i) the canonical grounding instance of the generator
    exact T1810_as_generator p_X h_norm parts h_disjoint h_cover
  · -- (ii) ground ∑π = 1 from T.18.10 (R4_Agent1), then run the generator instance
    obtain ⟨_, hπ_sum⟩ :=
      MIP.R4_Agent1_OhmConservationCoupling.subdomain_masses_normalised
        p_X h_norm parts h_disjoint h_cover
    exact product_mass_from_generator s₁ parts q
      (fun S => ((∑ ω ∈ S, p_X ω : NNReal) : ℝ)) hq_sum hπ_sum
  · -- (iii) the R.132 instance of the generator
    exact R132_from_generator B u v N N_star N_bi Asym
      h_N h_Nstar h_N_bi h_Asym

end R5_Agent1_ConservationUniqueGenerator

end MIP
