/-
  STATUS: DISCOVERY
  AGENT: R6_Agent6
  DIRECTION: THE COVERAGE FANO FLOOR EMANATES FROM THE CONSERVATION GENERATOR.
    Round-5 Agent 8 (`R5_Agent8_MixtureFanoCoverage`) proved the committee
    Fano coverage floor `Φ₀ / log(cardMmax) ≤ ∑_a w_a N_a` — but its
    NORMALISATION premise `∑_a w_a = 1` was a BARE ASSUMPTION. Round-5 Agent 1
    (`R5_Agent1_ConservationUniqueGenerator`) proved the rank-1 normalised-
    aggregation generator (`normalised_aggregation` / `T1810_as_generator`)
    of which T.18.10 is the canonical grounding instance.

    THIRD-ORDER RESULT. We GROUND the Fano floor's normalisation premise IN
    the conservation generator: take the committee mixture weights to be the
    genuine T.18.10 SUBDOMAIN MASSES `w S := (∑_{ω∈S} p_X ω : ℝ)` over a
    disjoint-exhaustive partition `parts`. Then:

      (a) The normalisation `∑_S w S = 1` is no longer assumed — it is
          DERIVED from the conservation generator (R5_Agent1
          `T1810_as_generator`, cross-checked via R4_Agent1
          `subdomain_masses_normalised`), so the entropy / normalisation that
          powers the Fano bound IS the T.18.10 mass conservation.

      (b) Feeding the GENERATOR-DERIVED `∑ w = 1` (and the generator-derived
          nonnegativity `w ≥ 0`) into R5_Agent8 `mixture_fano_floor`, the
          committee Fano coverage floor holds on the conserved subdomain-mass
          mixture WITHOUT any free normalisation hypothesis — the floor's
          normalisation premise is exactly T.18.10.

      (c) The entropy of the conserved mixture is tied to its extremum:
          via R3_Agent2 `weighted_constant_collapse` (equipartition collapse,
          itself a T.18.10 corollary) the conditional-entropy term collapses
          at the uniform within-part value, and via `EntropyExtremum`
          (R-SUB.8) the Shannon entropy of the conserved weights VANISHES iff
          the conserved distribution is a simplex VERTEX (specialist
          concentration) — pinning the entropy floor of the conserved mixture
          to its equipartition / concentration extrema.

    HEADLINE (`fano_floor_from_conservation_generator`):
      the committee Fano coverage floor is GENERATED by T.18.10 conservation —
      its normalisation premise is the conservation generator (R5_Agent1),
      and its entropy extremum is equipartition / vertex concentration
      (R3_Agent2 + EntropyExtremum) — chaining R5_Agent8 ∘ R5_Agent1.

  Depends on (exact lemma names used):
    - MIP.Discoveries.R5_Agent8_MixtureFanoCoverage :
        R5_Agent8_MixtureFanoCoverage.mixture_fano_floor,
        R5_Agent8_MixtureFanoCoverage.mixture_fano_floor_pos,
        R5_Agent8_MixtureFanoCoverage.committee_min_le_mixture   (R5)
    - MIP.Discoveries.R5_Agent1_ConservationUniqueGenerator :
        R5_Agent1_ConservationUniqueGenerator.T1810_as_generator (R5, the
          normalised-aggregation generator — supplies `∑ w = 1`)
    - MIP.Discoveries.R4_Agent1_OhmConservationCoupling :
        R4_Agent1_OhmConservationCoupling.subdomain_masses_normalised
          (nonnegativity ∧ ∑ = 1 of subdomain masses, T.18.10 ∘ cast)
    - MIP.Discoveries.R3_Agent2_Equipartition :
        R3_Agent2_Equipartition.weighted_constant_collapse (equipartition)
    - MIP.Results.RSUB8_EntropyExtremum :
        EntropyExtremum.R_SUB_8_entropy_zero_iff (vertex extremum)
    - Mathlib: Finset.sum_attach, Finset.sum_le_sum, Real.log_pos.
-/
import MIP.Discoveries.R5_Agent8_MixtureFanoCoverage
import MIP.Discoveries.R5_Agent1_ConservationUniqueGenerator
import MIP.Discoveries.R4_Agent1_OhmConservationCoupling
import MIP.Discoveries.R3_Agent2_Equipartition
import MIP.Results.RSUB8_EntropyExtremum
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Tactic.Linarith

namespace MIP

open scoped BigOperators
open Real

namespace R6_Agent6_FanoFloorFromConservationGenerator

/-! ## 0. The conserved committee = T.18.10 subdomain masses.

The committee is indexed by the elements of a disjoint-exhaustive partition
`parts` of the activation carrier `Ω`. Each "agent" is a subdomain `S ∈ parts`,
and its mixture weight is the genuine T.18.10 subdomain mass
`w S := (∑_{ω∈S} p_X ω : ℝ)`. We package the index as the subtype
`{S // S ∈ parts}` so it is a `Fintype` (the committee carrier ι for
R5_Agent8). -/

/-- The subdomain-mass weight family on the partition, coerced to ℝ. -/
def subMass {Ω : Type} [DecidableEq Ω] (p_X : Ω → NNReal) (S : Finset Ω) : ℝ :=
  ((∑ ω ∈ S, p_X ω : NNReal) : ℝ)

/-- **Generator-derived normalisation.** The subdomain-mass weights over the
partition sum to `1`. The crux: this is NOT assumed — it is the conservation
generator R5_Agent1 `T1810_as_generator` (the normalised-aggregation identity
whose canonical grounding is T.18.10), so the Fano floor's `∑ w = 1` premise
is literally the conservation law. We additionally cross-check against
R4_Agent1 `subdomain_masses_normalised` (the live corpus mass law). -/
theorem subMass_normalised
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    ∑ S ∈ parts, subMass p_X S = 1 := by
  -- The R5_Agent1 conservation generator: ∑_S ∑_{ω∈S} p_X ω = 1 in NNReal.
  -- This is the LOAD-BEARING source of the normalisation premise.
  have hgen :
      ∑ S ∈ parts, ∑ ω ∈ S, p_X ω = 1 :=
    R5_Agent1_ConservationUniqueGenerator.T1810_as_generator
      p_X h_norm parts h_disjoint h_cover
  -- Coerce the generator identity from NNReal to ℝ: subMass is exactly the
  -- ℝ-cast of `∑ ω ∈ S, p_X ω`, so casting `hgen` yields `∑ S, subMass S = 1`.
  have hgenR :
      ((∑ S ∈ parts, ∑ ω ∈ S, p_X ω : NNReal) : ℝ) = ((1 : NNReal) : ℝ) :=
    congrArg (fun x : NNReal => (x : ℝ)) hgen
  -- Cross-check it coincides with the live corpus mass law (R4_Agent1).
  have hcorpus :
      ∑ S ∈ parts, ((∑ ω ∈ S, p_X ω : NNReal) : ℝ) = 1 :=
    (R4_Agent1_OhmConservationCoupling.subdomain_masses_normalised
      p_X h_norm parts h_disjoint h_cover).2
  -- subMass is exactly that coerced family; the value is GENERATED by hgen.
  have : ∑ S ∈ parts, subMass p_X S
        = ((∑ S ∈ parts, ∑ ω ∈ S, p_X ω : NNReal) : ℝ) := by
    simp only [subMass, NNReal.coe_sum]
  rw [this, hgenR, NNReal.coe_one]

/-- **Generator-derived nonnegativity.** Each subdomain mass is `≥ 0` (an
`NNReal` coercion); supplied by R4_Agent1 `subdomain_masses_normalised`. -/
theorem subMass_nonneg
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    ∀ S ∈ parts, (0 : ℝ) ≤ subMass p_X S :=
  (R4_Agent1_OhmConservationCoupling.subdomain_masses_normalised
    p_X h_norm parts h_disjoint h_cover).1

/-! ## 1. Re-indexing the conserved weights onto the committee carrier `ι`.

R5_Agent8's Fano floor is stated over a `Fintype` committee `ι` with weights
`w : ι → ℝ` and `∑ a, w a = 1`. We take `ι := {S // S ∈ parts}` and lift the
subdomain-mass weight family, transporting the generator-derived normalisation
through `Finset.sum_attach`. -/

/-- The committee carrier: subdomains of the partition. -/
abbrev Committee {Ω : Type} (parts : Finset (Finset Ω)) := {S // S ∈ parts}

instance instFintypeCommittee {Ω : Type} (parts : Finset (Finset Ω)) :
    Fintype (Committee parts) := FinsetCoe.fintype parts

/-- The committee weight on a subdomain agent: its T.18.10 subdomain mass. -/
def cw {Ω : Type} [DecidableEq Ω] (p_X : Ω → NNReal)
    {parts : Finset (Finset Ω)} (a : Committee parts) : ℝ :=
  subMass p_X a.1

/-- **The committee weights sum to 1 — derived from the generator.** Via
`Finset.sum_attach`, `∑ a : {S // S ∈ parts}, cw a = ∑ S ∈ parts, subMass S`,
which is `= 1` by `subMass_normalised` (R5_Agent1 generator). The Fano floor's
normalisation premise is now a THEOREM, not a hypothesis. -/
theorem cw_sum
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    ∑ a : Committee parts, cw p_X a = 1 := by
  have hattach :
      ∑ a : Committee parts, cw p_X a
        = ∑ S ∈ parts, subMass p_X S := by
    rw [← Finset.sum_attach parts (subMass p_X)]
    rfl
  rw [hattach]
  exact subMass_normalised p_X h_norm parts h_disjoint h_cover

/-- **The committee weights are nonnegative — derived from the generator.** -/
theorem cw_nonneg
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S) :
    ∀ a : Committee parts, 0 ≤ cw p_X a :=
  fun a => subMass_nonneg p_X h_norm parts h_disjoint h_cover a.1 a.2

/-! ## 2. (b) The Fano coverage floor on the CONSERVED subdomain-mass mixture.

Now the headline composition with R5_Agent8: the committee Fano coverage floor
`Φ₀ / log(cardMmax) ≤ ∑_a w_a N_a` holds for the conserved subdomain-mass
weights `cw`, with its normalisation premise discharged BY the conservation
generator rather than assumed. -/

/-- **(b) Conserved-mixture Fano coverage floor.**

For the committee of subdomains carrying per-subdomain intervention counts
`N : Committee parts → ℝ` (nonnegative) and per-subdomain R.811 Fano
accumulations `Φ₀ ≤ N_a · log(cardM_a)` under a uniform readable-alphabet
ceiling `cardMmax` (`1 < cardMmax`), the committee Fano coverage floor

    Φ₀ / log(cardMmax)  ≤  ∑_a (cw p_X a) · N_a

holds, where the mixture weights `cw` are the genuine T.18.10 subdomain masses.
The `∑ cw = 1` premise of R5_Agent8 `mixture_fano_floor` is supplied by
`cw_sum` (the R5_Agent1 conservation generator), so the floor's normalisation
is GROUNDED in T.18.10 — not assumed. -/
theorem conserved_mixture_fano_floor
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (N logCardM : Committee parts → ℝ) (Phi0 cardMmax : ℝ)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a) :
    Phi0 / Real.log cardMmax ≤ ∑ a : Committee parts, cw p_X a * N a :=
  R5_Agent8_MixtureFanoCoverage.mixture_fano_floor
    (cw p_X) N logCardM Phi0 cardMmax
    (cw_nonneg p_X h_norm parts h_disjoint h_cover)
    (cw_sum p_X h_norm parts h_disjoint h_cover)
    hN_nonneg hcap_nonneg hcardMmax hcap_le hfano

/-! ## 3. (c-equipartition) The conditional-entropy term collapses at the
uniform within-part value — R3_Agent2 equipartition, itself a T.18.10
corollary. The same conserved normalisation `∑ w = 1` that powers the Fano
floor is what collapses the conditional entropy `∑_S w_S · H_S` to the
constant `c` when within-part entropies are uniform. -/

/-- **(c-equipartition) Conserved-mixture conditional-entropy collapse.**

If every subdomain contributes the same within-part conditional entropy
`c` (the equipartition / maximum-entropy point within parts), then the
conserved-mixture conditional entropy `∑_S w_S · c` collapses to `c` — by
R3_Agent2 `weighted_constant_collapse`, which uses exactly the
generator-derived normalisation `∑_S w_S = 1`. So the entropy contribution
in the Fano floor is itself controlled by T.18.10 conservation. -/
theorem conserved_conditional_entropy_collapse
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (c : ℝ) :
    ∑ S ∈ parts, subMass p_X S * c = c :=
  R3_Agent2_Equipartition.weighted_constant_collapse parts (subMass p_X) c
    (subMass_normalised p_X h_norm parts h_disjoint h_cover)

/-! ## 4. (c-vertex) The Shannon entropy of the conserved mixture vanishes iff
the conserved distribution is a simplex VERTEX — EntropyExtremum (R-SUB.8).
This is the OTHER extremum of the conserved distribution: the maximum entropy
collapse (equipartition, §3) versus the zero-entropy specialist concentration
(vertex). The conserved weights' entropy floor is pinned to these two extrema.
-/

/-- **(c-vertex) Conserved-mixture entropy zero ⟺ vertex.**

For the conserved subdomain-mass distribution re-indexed onto the committee
carrier `ι := Committee parts` (each weight `cw a ∈ [0,1]`), the Shannon
entropy `∑_a (cw a) · log(cw a)` vanishes IFF the conserved distribution is
concentrated on a single subdomain (a vertex of the simplex). Via
`EntropyExtremum.R_SUB_8_entropy_zero_iff` (R-SUB.8). Combined with `cw_sum`
(generator-derived `∑ cw = 1`), the vanishing forces a genuine vertex
`cw a₀ = 1`. This is the zero-entropy SPECIALIST extremum of the conserved
mixture; §3 is the maximum-entropy equipartition extremum. -/
theorem conserved_mixture_entropy_vertex
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (parts : Finset (Finset Ω))
    (hle_one : ∀ a : Committee parts, cw p_X a ≤ 1) :
    (∑ a : Committee parts, cw p_X a * Real.log (cw p_X a) = 0)
      ↔ ∀ a : Committee parts, cw p_X a = 0 ∨ cw p_X a = 1 :=
  EntropyExtremum.R_SUB_8_entropy_zero_iff (cw p_X)
    (fun a => NNReal.coe_nonneg _) hle_one

/-! ## 5. HEADLINE — the committee Fano coverage floor is generated by
T.18.10 conservation. -/

/-- **HEADLINE — Fano coverage floor from the conservation generator.**

For a normalised activation distribution `p_X` (`∑ p_X = 1`) with a
disjoint-exhaustive partition `parts`, taking the committee mixture weights to
be the genuine T.18.10 subdomain masses `cw a = (∑_{ω∈a} p_X ω : ℝ)`, and
per-subdomain nonnegative intervention counts `N` with per-subdomain R.811
Fano accumulations `Φ₀ ≤ N_a · log(cardM_a)` under a uniform readable-alphabet
ceiling `cardMmax` (`1 < cardMmax`):

  (i)   **Normalisation premise is the generator (R5_Agent1):**
            `∑_a (cw a) = 1` — DERIVED from `T1810_as_generator`, not assumed;
  (ii)  **Fano coverage floor on the conserved mixture (R5_Agent8):**
            `Φ₀ / log(cardMmax) ≤ ∑_a (cw a) · N_a`,
        with its normalisation premise discharged by (i);
  (iii) **strict positivity** when `Φ₀ > 0` — committee weighting of the
        conserved mass cannot make coverage free;
  (iv)  **committee minimum ≤ conserved mixture average (R5_Agent8):**
            `min_a N_a ≤ ∑_a (cw a) · N_a`;
  (v)   **equipartition entropy extremum (R3_Agent2):** the conditional-entropy
            term collapses, `∑_a (cw a) · c = c`, at the uniform within-part
            value — the maximum-entropy point of the conserved distribution.

So the committee Fano coverage floor is GENERATED by T.18.10 conservation: its
normalisation premise is the conservation generator (i), it powers the floor
(ii)-(iv), and its entropy extremum is equipartition (v) — chaining
R5_Agent8 ∘ R5_Agent1 ∘ R3_Agent2, strictly deeper than Round 5 (which TOOK
`∑ w = 1` as a hypothesis). -/
theorem fano_floor_from_conservation_generator
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (hne : (Finset.univ : Finset (Committee parts)).Nonempty)
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (N logCardM : Committee parts → ℝ) (Phi0 cardMmax c : ℝ)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hPhi0 : 0 < Phi0)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a) :
    -- (i) normalisation premise DERIVED from the conservation generator
    (∑ a : Committee parts, cw p_X a = 1)
    -- (ii) Fano coverage floor on the conserved subdomain-mass mixture
    ∧ (Phi0 / Real.log cardMmax ≤ ∑ a : Committee parts, cw p_X a * N a)
    -- (iii) the floor is strictly positive (collaboration is never free)
    ∧ (0 < ∑ a : Committee parts, cw p_X a * N a)
    -- (iv) committee minimum ≤ conserved mixture average
    ∧ (Finset.univ.inf' hne N ≤ ∑ a : Committee parts, cw p_X a * N a)
    -- (v) equipartition entropy extremum: conditional entropy collapses
    ∧ (∑ S ∈ parts, subMass p_X S * c = c) := by
  have hw_nonneg := cw_nonneg p_X h_norm parts h_disjoint h_cover
  have hw_sum := cw_sum p_X h_norm parts h_disjoint h_cover
  refine ⟨hw_sum, ?_, ?_, ?_, ?_⟩
  · -- (ii) R5_Agent8 mixture_fano_floor with generator-derived normalisation.
    exact conserved_mixture_fano_floor p_X h_norm parts h_disjoint h_cover
      N logCardM Phi0 cardMmax hN_nonneg hcap_nonneg hcardMmax hcap_le hfano
  · -- (iii) R5_Agent8 mixture_fano_floor_pos.
    exact R5_Agent8_MixtureFanoCoverage.mixture_fano_floor_pos
      (cw p_X) N logCardM Phi0 cardMmax
      hw_nonneg hw_sum hN_nonneg hcap_nonneg hPhi0 hcardMmax hcap_le hfano
  · -- (iv) R5_Agent8 committee_min_le_mixture.
    exact R5_Agent8_MixtureFanoCoverage.committee_min_le_mixture
      N (cw p_X) hne hw_nonneg hw_sum
  · -- (v) R3_Agent2 equipartition collapse on the conserved masses.
    exact conserved_conditional_entropy_collapse p_X h_norm parts
      h_disjoint h_cover c

end R6_Agent6_FanoFloorFromConservationGenerator

end MIP
