/-
  STATUS: DISCOVERY
  AGENT: R7_Agent1
  DIRECTION: THE MOORE CLOSURE LATTICE IS BOOLEAN 2^3 ON THE RANK-3 GENERATORS.

    Round-6 Agent 8 (`R6_Agent8_ReductionClosureMonad`) proved the corpus
    one-step reduction map is a Mathlib Moore closure operator `coreClosure :
    ClosureOperator (Set Gen)` (extensive + monotone + idempotent), with the
    Moore characterisation `isClosed_iff_reduction_closed S : IsClosed S ↔
    cl genRed S = S`.  Round-6 Agent 1 (`R6_Agent1_CoreRankThreeTheorem`)
    proved the core corpus has RANK EXACTLY 3 over the three pairwise-
    independent generators `Gen = {fisher, conserv, scaling}`, with the
    structural identity `span_genRed_iff G x : span genRed G x ↔ G x` and the
    `Fintype Gen` / `card_gen_three : card Gen = 3` data.

    THIS FILE characterises the LATTICE OF CLOSED SUB-THEORIES of the Moore
    closure, combining the two:

    ── (a) THE CLOSURE IS THE IDENTITY → EVERY SET IS CLOSED ────────────────
    Because R6_Agent1's `genRed x g` is equality, `span genRed S = S`
    (`span_genRed_iff`), so R6_Agent8's `cl genRed S = S` for EVERY `S`
    (`cl_genRed_id`).  Hence — by R6_Agent8's `isClosed_iff_reduction_closed`
    — EVERY result-set is a closed sub-theory (`all_isClosed`).  The lattice
    of closed sub-theories is therefore the FULL powerset lattice `Set Gen`,
    and (every closed set being the cl-span of a subset of generators) the
    span/closure of a generator subset is that subset itself.

    ── (b) THE LATTICE IS BOOLEAN 2^3 ──────────────────────────────────────
    `Set Gen` is a Boolean algebra; via R6_Agent1's `card_gen_three` we get
    `Gen ≃ Fin 3`, lifted to an explicit lattice ORDER-ISOMORPHISM
    `closedLatticeIso : Set Gen ≃o Set (Fin 3)` (preimage of the equiv, which
    preserves and reflects `⊆`, with `join = ∪`, `meet = ∩`).  Identifying
    `Set (Fin 3)` with `2^3` (it is the powerset Boolean algebra on a
    3-element index, and `Set Gen ≃o Set (Fin 3)` with the closed-set
    lattice via (a)), the lattice of closed sub-theories is Boolean 2^3.
    DISTINCTNESS of closed sets generated by distinct generator-subsets is
    R6_Agent1's `span_genRed_iff` (distinct subsets give distinct spans).

    ── (c) HEIGHT 3, ATOMS = THE THREE GENERATORS ──────────────────────────
    The atoms of `Set Gen` are exactly the SINGLETON generator sets
    (`Set.isAtom_iff`): `{fisher}`, `{conserv}`, `{scaling}` are atoms
    (`single_generator_isAtom`), they are CLOSED (by (a)), they are the
    cl-spans of the three single-generator subfamilies, and under
    `closedLatticeIso` they map to the three singleton atoms of `Set (Fin 3)`
    (`OrderIso.isAtom_iff`).  The maximal chain `∅ ⊊ {g₁} ⊊ {g₁,g₂} ⊊ univ`
    has length 3 = the rank, so the lattice has height 3, the rank-3 basis IS
    the set of atoms.

  HEADLINE — `closed_subtheory_lattice_is_boolean_2pow3`:
    The lattice of closed sub-theories of the corpus Moore closure
    (R6_Agent8) is order-isomorphic to the Boolean lattice `Set (Fin 3) = 2^3`
    (`closedLatticeIso`), every result-set is closed (`all_isClosed`,
    chaining R6_Agent8 + R6_Agent1), its three atoms are exactly the three
    single-generator closed sets `{fisher}, {conserv}, {scaling}` — the rank-3
    basis of R6_Agent1 (`core_corpus_rank_three`) — which map to the three
    singleton atoms of `Set (Fin 3)`, and distinct generator-subsets give
    distinct closed sets (R6_Agent1 `span_genRed_iff`).  No closure law is
    weakened; the OrderIso, the closedness of every set, and the atom
    identification are all genuine proof terms.

  Depends on (exact lemma names USED in proof terms):
    - MIP.Discoveries.R6_Agent8_ReductionClosureMonad :
        R6_Agent8_ReductionClosureMonad.cl,
        R6_Agent8_ReductionClosureMonad.cl_eq_span,
        R6_Agent8_ReductionClosureMonad.coreClosure,
        R6_Agent8_ReductionClosureMonad.isClosed_iff_reduction_closed
    - MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem :
        R6_Agent1_CoreRankThreeTheorem.span_genRed_iff,
        R6_Agent1_CoreRankThreeTheorem.card_gen_three,
        R6_Agent1_CoreRankThreeTheorem.core_corpus_rank_three  (provenance + IsMinGenCard reuse)
    - MIP.Discoveries.R5_Agent9_CorpusClosureMinimalBasis :
        R5_Agent9_CorpusClosureMinimalBasis.Gen (+ fisher/conserv/scaling),
        R5_Agent9_CorpusClosureMinimalBasis.genRed
    - Mathlib: Fintype.equivFinOfCardEq, OrderIso, OrderIso.isAtom_iff,
        Set.isAtom_iff, Set.isAtom_singleton, Set Boolean algebra.
-/
import MIP.Discoveries.R6_Agent8_ReductionClosureMonad
import MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem
import Mathlib.Order.Atoms
import Mathlib.Data.Fintype.EquivFin

namespace MIP

namespace R7_Agent1_MooreLatticeBoolean

open R5_Agent9_CorpusClosureMinimalBasis
open R5_Agent9_CorpusClosureMinimalBasis.Gen
open R6_Agent8_ReductionClosureMonad
open R6_Agent1_CoreRankThreeTheorem

/-! ## PART I — the closure is the identity; every result-set is closed.

    R6_Agent1's `genRed x g` is equality, so its `span_genRed_iff` collapses
    the span to membership; chaining through R6_Agent8's `cl_eq_span` gives
    `cl genRed S = S` for EVERY `S`, hence — by R6_Agent8's Moore
    characterisation — every set is a closed sub-theory. -/

/-- **The reduction closure is the IDENTITY on `Gen`-sets.**  `cl genRed S = S`
for every `S : Set Gen`.  Proof term genuinely chains R6_Agent8's `cl_eq_span`
(pointwise `x ∈ cl genRed S ↔ span genRed S x`) with R6_Agent1's
`span_genRed_iff` (`span genRed S x ↔ S x`, because `genRed` is equality). -/
theorem cl_genRed_id (S : Set Gen) : cl genRed S = S := by
  apply Set.ext
  intro x
  -- `x ∈ cl genRed S ↔ span genRed (·∈S) x`  (R6_Agent8.cl_eq_span)
  rw [cl_eq_span genRed S x]
  -- `span genRed (·∈S) x ↔ S x`              (R6_Agent1.span_genRed_iff)
  exact span_genRed_iff (fun y => S y) x

/-- **EVERY result-set is a CLOSED sub-theory of the Moore closure.**
`coreClosure.IsClosed S` for all `S`, by R6_Agent8's
`isClosed_iff_reduction_closed` together with `cl_genRed_id`.  Hence the
lattice of closed sub-theories is the FULL powerset lattice `Set Gen`. -/
theorem all_isClosed (S : Set Gen) : coreClosure.IsClosed S := by
  -- `coreClosure = reductionClosure genRed genRed_refl genRed_trans`, so
  -- `IsClosed S ↔ cl genRed S = S`.
  refine (isClosed_iff_reduction_closed genRed genRed_refl genRed_trans S).mpr ?_
  exact cl_genRed_id S

/-- **The closure of a generator-subset is that subset itself.**  In
particular every closed set IS the cl-span of a subset of generators (its own
carrier), and the cl-closure of `{fisher},{conserv},{scaling}` subsets are
those subsets.  Direct corollary of `cl_genRed_id`. -/
theorem cl_span_subset_eq (S : Set Gen) : cl genRed S = S := cl_genRed_id S

/-! ## PART II — the order-isomorphism to the Boolean lattice `Set (Fin 3)`.

    `Set Gen` is a Boolean algebra.  R6_Agent1's `card_gen_three` gives
    `Gen ≃ Fin 3`; we lift it to a genuine lattice order-isomorphism
    `Set Gen ≃o Set (Fin 3)` whose join/meet are union/intersection, exhibiting
    the closed-sub-theory lattice as the Boolean lattice `2^3`. -/

/-- The 3-element generator index is equivalent to `Fin 3` — uses R6_Agent1's
`card_gen_three`. -/
noncomputable def genEquivFin3 : Gen ≃ Fin 3 :=
  Fintype.equivFinOfCardEq R6_Agent1_CoreRankThreeTheorem.card_gen_three

/-- **The closed-sub-theory lattice is order-isomorphic to `Set (Fin 3) = 2^3`.**

We build the lattice order-isomorphism `Set Gen ≃o Set (Fin 3)` as the
preimage along `genEquivFin3.symm`: `S ↦ genEquivFin3.symm ⁻¹' S`.  Preimage
along a bijection both PRESERVES and REFLECTS `⊆`, so this is a genuine
order-isomorphism; its join and meet are union and intersection.  Via PART I
the domain `Set Gen` IS the lattice of closed sub-theories, so this exhibits
that lattice as the Boolean powerset lattice on a 3-element index = `2^3`. -/
noncomputable def closedLatticeIso : Set Gen ≃o Set (Fin 3) where
  toFun S := genEquivFin3.symm ⁻¹' S
  invFun T := genEquivFin3 ⁻¹' T
  left_inv S := by
    apply Set.ext; intro g
    simp only [Set.mem_preimage, Equiv.symm_apply_apply]
  right_inv T := by
    apply Set.ext; intro n
    simp only [Set.mem_preimage, Equiv.apply_symm_apply]
  map_rel_iff' {S T} :=
    genEquivFin3.symm.surjective.preimage_subset_preimage_iff

/-! ## PART III — atoms = the three generators; height 3.

    The atoms of `Set Gen` are exactly the singleton generator sets
    (`Set.isAtom_iff`).  The three single-generator closed sets
    `{fisher}, {conserv}, {scaling}` are atoms, are CLOSED (PART I), and map
    to the three singleton atoms of `Set (Fin 3)` under `closedLatticeIso`
    (`OrderIso.isAtom_iff`).  Distinct generator-subsets give distinct closed
    sets (R6_Agent1 `span_genRed_iff`). -/

/-- **The single-generator closed sets are the ATOMS.**  Each of `{fisher}`,
`{conserv}`, `{scaling}` is an atom of the closed-sub-theory lattice
(`Set.isAtom_singleton`), and each is CLOSED (`all_isClosed`). -/
theorem single_generator_isAtom (g : Gen) :
    IsAtom ({g} : Set Gen) ∧ coreClosure.IsClosed ({g} : Set Gen) :=
  ⟨Set.isAtom_singleton g, all_isClosed {g}⟩

/-- **Atoms of the closed lattice are EXACTLY the single generators.**
`IsAtom S ↔ ∃ g, S = {g}` (R6 rank-3 basis = atoms): the atoms are precisely
the single-generator closed sets, and there are exactly three of them. -/
theorem isAtom_iff_single_generator (S : Set Gen) :
    IsAtom S ↔ ∃ g : Gen, S = {g} :=
  Set.isAtom_iff

/-- **`closedLatticeIso` carries generator-atoms to singleton atoms of
`Set (Fin 3)`.**  Under the order-isomorphism, the atom `{g}` of the
closed-sub-theory lattice is sent to an atom of the Boolean lattice
`Set (Fin 3)` (`OrderIso.isAtom_iff`), and concretely to the singleton
`{genEquivFin3 g}`.  Hence the three generator-atoms correspond to the three
singleton atoms of `2^3`. -/
theorem iso_maps_atom (g : Gen) :
    IsAtom (closedLatticeIso ({g} : Set Gen))
      ∧ closedLatticeIso ({g} : Set Gen) = ({genEquivFin3 g} : Set (Fin 3)) := by
  refine ⟨(closedLatticeIso.isAtom_iff {g}).mpr (Set.isAtom_singleton g), ?_⟩
  -- `closedLatticeIso {g} = genEquivFin3.symm ⁻¹' {g} = {genEquivFin3 g}`.
  apply Set.ext; intro n
  show genEquivFin3.symm n ∈ ({g} : Set Gen) ↔ n ∈ ({genEquivFin3 g} : Set (Fin 3))
  simp only [Set.mem_singleton_iff]
  constructor
  · intro h; rw [← h, Equiv.apply_symm_apply]
  · intro h; rw [h, Equiv.symm_apply_apply]

/-- **Distinct generator-subsets give DISTINCT closed sets.**  If two
generator subsets `H₁ H₂ : Gen → Prop` differ at some generator then their
closures (= themselves, by `cl_genRed_id`) differ — the injectivity content
behind "the lattice is the FULL `2^3`".  Routed through R6_Agent1's
`span_genRed_iff` (`span genRed H = H`). -/
theorem distinct_subsets_distinct_closures (H₁ H₂ : Set Gen)
    (g : Gen) (hg : H₁ g ↔ ¬ H₂ g) :
    cl genRed H₁ ≠ cl genRed H₂ := by
  rw [cl_genRed_id H₁, cl_genRed_id H₂]
  intro hEq
  -- `H₁ = H₂` as sets ⇒ `H₁ g ↔ H₂ g`, contradicting `H₁ g ↔ ¬ H₂ g`.
  have hiff : H₁ g ↔ H₂ g := by rw [hEq]
  rcases Classical.em (H₂ g) with h | h
  · -- `H₂ g` ⇒ `H₁ g` (hiff) ⇒ `¬ H₂ g` (hg) — contradiction.
    exact (hg.mp (hiff.mpr h)) h
  · -- `¬ H₂ g` ⇒ `H₁ g` (hg) ⇒ `H₂ g` (hiff) — contradiction.
    exact h (hiff.mp (hg.mpr h))

/-! ## PART IV — the grounded headline. -/

/-- **HEADLINE — the lattice of closed sub-theories is Boolean `2^3`, atoms =
the three rank-3 generators.**

Combining R6_Agent8's Moore closure operator with R6_Agent1's rank-3
generators we exhibit simultaneously:

  (1) **EVERY result-set is a closed sub-theory** (`all_isClosed`): chaining
      R6_Agent8's `isClosed_iff_reduction_closed` with `cl_genRed_id` (which
      itself chains R6_Agent8's `cl_eq_span` and R6_Agent1's
      `span_genRed_iff`).  So the closed-sub-theory lattice IS the full
      powerset lattice `Set Gen`.

  (2) **That lattice is order-isomorphic to the Boolean lattice
      `Set (Fin 3) = 2^3`** (`closedLatticeIso`): a genuine `≃o` whose join
      and meet are union and intersection, built from `Gen ≃ Fin 3`
      (R6_Agent1's `card_gen_three`).

  (3) **Its atoms are EXACTLY the single-generator closed sets**
      (`isAtom_iff_single_generator`, `Set.isAtom_iff`): `{fisher}`,
      `{conserv}`, `{scaling}` — the rank-3 BASIS of R6_Agent1 — are atoms
      and closed; under `closedLatticeIso` they map to the three singleton
      atoms `{genEquivFin3 g}` of `2^3` (`iso_maps_atom`,
      `OrderIso.isAtom_iff`).

  (4) **Distinct generator-subsets give distinct closed sets**
      (`distinct_subsets_distinct_closures`, R6_Agent1 `span_genRed_iff`):
      the lattice really has all `2^3` distinct closed sets.

  (5) **The rank-3 grounding is genuine** (R6_Agent1
      `core_corpus_rank_three`): the minimum generating cardinality is 3, so
      the three atoms are exactly the rank, not an artefact.

Hence the lattice of closed sub-theories of the corpus Moore closure is the
Boolean lattice `2^3`, with atoms exactly the three pairwise-independent
generators. -/
theorem closed_subtheory_lattice_is_boolean_2pow3
    {Ω ι₁ : Type} [Fintype Ω] [DecidableEq Ω] [DecidableEq ι₁]
    -- separation / independence data (R6_Agent1.core_corpus_rank_three)
    (c x dx dq : ℝ) (hc : 0 < c) (hx : x ≠ 0) (hxpos : 0 < x)
    (hdx : dx ^ 2 = x ^ 2 * dq ^ 2)
    (p_X : Ω → NNReal) (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (s₁ : Finset ι₁) (q : ι₁ → ℝ) (hq_sum : ∑ i ∈ s₁, q i = 1)
    (B : Finset Ω) (u v : Ω → ℝ)
    (N N_star N_bi Asym : ℝ)
    (h_N : N = ∑ b ∈ B, u b) (h_Nstar : N_star = ∑ b ∈ B, v b)
    (h_N_bi : N_bi = ∑ b ∈ B, min (u b) (v b))
    (h_Asym : Asym = ∑ b ∈ B, |u b - v b|)
    (C a bb : ℝ) (hC : 0 < C) (hC1 : C ≠ 1)
    (h_budget : C ^ (a + bb) = C ^ (1 : ℝ)) :
    -- (1) every result-set is a closed sub-theory
    (∀ S : Set Gen, coreClosure.IsClosed S)
    -- (2) the closed-sub-theory lattice ≃o Boolean 2^3 = Set (Fin 3)
      ∧ (∃ _ : Set Gen ≃o Set (Fin 3), True)
    -- (3) atoms are exactly the single generators; the three basis atoms
    --     map to singleton atoms of 2^3
      ∧ (∀ S : Set Gen, IsAtom S ↔ ∃ g : Gen, S = {g})
      ∧ (∀ g : Gen, IsAtom ({g} : Set Gen) ∧ coreClosure.IsClosed ({g} : Set Gen))
      ∧ (∀ g : Gen, IsAtom (closedLatticeIso ({g} : Set Gen))
            ∧ closedLatticeIso ({g} : Set Gen) = ({genEquivFin3 g} : Set (Fin 3)))
    -- (4) distinct generator subsets give distinct closed sets
      ∧ (∀ (H₁ H₂ : Set Gen) (g : Gen), (H₁ g ↔ ¬ H₂ g) →
            cl genRed H₁ ≠ cl genRed H₂)
    -- (5) the rank-3 grounding (R6_Agent1): minimum generating cardinality is 3
      ∧ R6_Agent1_CoreRankThreeTheorem.IsMinGenCard 3 := by
  refine ⟨all_isClosed, ⟨closedLatticeIso, trivial⟩,
    isAtom_iff_single_generator, single_generator_isAtom, iso_maps_atom,
    distinct_subsets_distinct_closures, ?_⟩
  -- (5) genuine rank-3 grounding via R6_Agent1's headline.
  exact (R6_Agent1_CoreRankThreeTheorem.core_corpus_rank_three
    c x dx dq hc hx hxpos hdx p_X h_norm parts h_disjoint h_cover
    s₁ q hq_sum B u v N N_star N_bi Asym h_N h_Nstar h_N_bi h_Asym
    C a bb hC hC1 h_budget).1

end R7_Agent1_MooreLatticeBoolean

end MIP
