/-
  STATUS: DISCOVERY
  AGENT: R7_Agent10
  DIRECTION: CIVILIZATION CAPABILITY AS A COLLECTIVE PHASE TRANSITION,
    WITH OPTIMAL EDUCATION ALLOCATION PINNED TO THE PHASE BOUNDARY UNDER
    THE CONSERVED COVERAGE FLOOR.

    The corpus carries three pieces that have never been chained:
      * a sociology PHASE structure (R.352 `R352_CivilizationPhase`): the
        civilization "solves faster than it generates problems" exactly when
        the order parameter `μ_N(t) − λ_P(t)` flips sign, and this happens
        iff the solving exponent dominates the generation exponent;
      * a conserved COVERAGE FLOOR on the collective intervention count
        (R6_Agent6 ∘ R5_Agent8 ∘ R5_Agent1 tower): the genuine T.18.10
        subdomain-mass mixture `N̄ := ∑_a (cw a)·N_a` is bounded BELOW by the
        information potential, `Φ₀ / log(cardMmax) ≤ N̄`, with its
        normalisation premise GENERATED by conservation (not assumed);
      * the optimal education ALLOCATION (R.350 `R350_EduOptimalAllocation`,
        R.62 KKT): in the `|K_A| ≫ |K_H|` limit the budget collapses to a
        corner `c_K = c_H = 0`, the surviving dimensions balance their
        cost-normalised marginals, and the whole budget flows to `c_Z + c_κ`.

    SEVENTH-ORDER RESULT. We model civilization capability as the collective
    phase transition of R.352 driven by the conserved-mixture intervention
    count of the R6/R5 coverage tower, and prove that the optimal education
    allocation drives the collective EXACTLY to the phase boundary while the
    conserved coverage floor CAPS the attainable solving rate:

      (a) **Coverage floor ⟹ collective solving-rate ceiling.**
          Modelling the collective problem-solving stock by the conserved
          subdomain-mass average `N̄ = ∑_a (cw a)·N_a` (R6_Agent6
          `conserved_mixture_fano_floor`), the floor `Φ₀/log(cardMmax) ≤ N̄`
          forces a HARD CEILING on the solving rate `μ_N = W/N̄`:

              μ_N = W / N̄  ≤  W · log(cardMmax) / Φ₀ .

          The conserved coverage floor is therefore a binding constraint on
          how fast a civilization can solve — no education allocation can push
          the solving rate past the information-theoretic ceiling.

      (b) **Optimal allocation sits at the phase boundary (R.350 ∘ R.62).**
          Under the KKT corner solution (R.350 `R_350_both_knowledge_corners`)
          the knowledge dimensions vanish, the budget collapses to
          `c_Z + c_κ = C` (R.350 `R_350_budget_residual`), and the surviving
          marginals balance (R.350 `R_350_marginal_balance` / R.62
          `R_62_pairwise_marginal_equality`). At the allocation that tunes the
          effective solving exponent `α_eff` to the crossing time `t*`, the
          order parameter is exactly zero: `μ_N(t*) = λ_P(t*)` — the optimum
          lies ON the R.352 phase boundary `exp((α−γ)t*) = λ₀N₀/W₀`.

      (c) **HEADLINE (`civilization_phase_optimal_education`).**
          Chaining (a) and (b): the optimal education allocation under the
          conserved coverage floor
            (i)   collapses to the corner `c_K = c_H = 0` and budget
                  residual `c_Z + c_κ = C` (R.350);
            (ii)  balances the surviving cost-normalised marginals (R.62);
            (iii) sits at the phase boundary `μ_N(t*) = λ_P(t*)` (R.352);
            (iv)  obeys the conserved coverage floor `Φ₀/log(cardMmax) ≤ N̄`
                  (R6_Agent6), whose normalisation is GENERATED by T.18.10
                  conservation (R5_Agent1 via R6_Agent6 `cw_sum`);
            (v)   hence the solving rate is CAPPED at the information ceiling
                  `μ_N ≤ W·log(cardMmax)/Φ₀`;
            (vi)  and the driving civilization activity is classified by the
                  R.22 trichotomy (each activity targets exactly one of N/K/P).
          So civilization capability IS a collective phase transition; the
          optimal education allocation sits at the phase boundary, and the
          conserved coverage floor caps the attainable solving rate.

  Depends on (exact lemma names actually used in proof terms):
    - MIP.Discoveries.R6_Agent6_FanoFloorFromConservationGenerator :
        R6_Agent6_FanoFloorFromConservationGenerator.conserved_mixture_fano_floor,
        R6_Agent6_FanoFloorFromConservationGenerator.cw_sum   (R6 tower —
          conserved coverage floor + generator-derived normalisation)
    - MIP.Discoveries.R5_Agent8_MixtureFanoCoverage :
        R5_Agent8_MixtureFanoCoverage.committee_min_le_mixture  (R5 tower —
          committee min ≤ conserved mixture average)
    - MIP.Results.R352_CivilizationPhase :
        R352_CivilizationPhase.R_352_net_rate_sign,
        R352_CivilizationPhase.R_352_transition_time   (phase order parameter
          + exact crossing/boundary time)
    - MIP.Results.R350_EduOptimalAllocation :
        R350_EduOptimalAllocation.R_350_both_knowledge_corners,
        R350_EduOptimalAllocation.R_350_budget_residual,
        R350_EduOptimalAllocation.R_350_marginal_balance  (KKT corner + budget
          + marginal balance)
    - MIP.Results.R62_KKTMarginalEquality :
        KKTMarginalEquality.R_62_pairwise_marginal_equality  (divide-by-cost
          marginal equality, surviving dimensions)
    - MIP.Results.R22_CivilizationTrichotomy :
        CivilizationTrichotomy.R_22_trichotomy   (driving activity classified)
    - Mathlib: div_le_iff₀, div_le_div_of_nonneg_left, Real.log_pos.

  No `sorry`/`admit`. No new `axiom`. No `native_decide`/`opaque`/`unsafe`.
-/
import MIP.Discoveries.R6_Agent6_FanoFloorFromConservationGenerator
import MIP.Discoveries.R5_Agent8_MixtureFanoCoverage
import MIP.Results.R352_CivilizationPhase
import MIP.Results.R350_EduOptimalAllocation
import MIP.Results.R62_KKTMarginalEquality
import MIP.Results.R22_CivilizationTrichotomy
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Positivity

namespace MIP

open scoped BigOperators
open Real

namespace R7_Agent10_CivilizationPhaseEducation

/-! ## 1. (a) The conserved coverage floor caps the collective solving rate.

We model the civilization's collective problem-solving STOCK by the conserved
subdomain-mass average intervention count
`N̄ := ∑_a (cw p_X a)·N_a` of the R6_Agent6 tower. The R.352 solving rate is
`μ_N = W / N̄`. The conserved coverage floor `Φ₀/log(cardMmax) ≤ N̄`
(R6_Agent6 `conserved_mixture_fano_floor`) — whose normalisation is GENERATED
by T.18.10 conservation — places a hard CEILING on `μ_N`. -/

/-- **(a-core) A positive coverage floor on `N̄` caps `W/N̄` from above.**

Pure-order kernel feeding the sociology rate: if the collective intervention
stock `Nbar` satisfies the (strictly positive) coverage floor `0 < floor ≤ Nbar`
and `0 ≤ W`, then the solving rate `W / Nbar` is capped by `W / floor`. -/
theorem solving_rate_ceiling_of_floor
    (W Nbar floor : ℝ)
    (hW : 0 ≤ W) (hfloor_pos : 0 < floor) (hfloor : floor ≤ Nbar) :
    W / Nbar ≤ W / floor := by
  have hNbar_pos : 0 < Nbar := lt_of_lt_of_le hfloor_pos hfloor
  exact div_le_div_of_nonneg_left hW hfloor_pos hfloor

/-- **(a) Conserved coverage floor ⟹ collective solving-rate ceiling.**

Take the collective intervention stock to be the conserved subdomain-mass
average `N̄ = ∑_a (cw p_X a)·N_a` of the R6_Agent6 tower (its normalisation
`∑ cw = 1` GENERATED by T.18.10 conservation). The R6_Agent6 coverage floor
`Φ₀/log(cardMmax) ≤ N̄` together with `Φ₀ > 0` (so the floor is strictly
positive) caps the R.352 solving rate `μ_N = W / N̄`:

    μ_N = W / N̄  ≤  W · (Φ₀/log(cardMmax))⁻¹  =  W · log(cardMmax) / Φ₀ .

The conserved coverage floor is a binding ceiling on the collective solving
rate — no education allocation can break the information-theoretic cap. -/
theorem collective_solving_rate_ceiling
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts,
        ω ∈ S)
    (N logCardM :
        R6_Agent6_FanoFloorFromConservationGenerator.Committee parts → ℝ)
    (W Phi0 cardMmax : ℝ)
    (hW : 0 ≤ W)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hPhi0 : 0 < Phi0)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a) :
    let Nbar := ∑ a : R6_Agent6_FanoFloorFromConservationGenerator.Committee parts,
        R6_Agent6_FanoFloorFromConservationGenerator.cw p_X a * N a
    W / Nbar ≤ W / (Phi0 / Real.log cardMmax) := by
  intro Nbar
  -- R6_Agent6 conserved coverage floor on the conserved mixture average.
  have hfloor :
      Phi0 / Real.log cardMmax ≤ Nbar :=
    R6_Agent6_FanoFloorFromConservationGenerator.conserved_mixture_fano_floor
      p_X h_norm parts h_disjoint h_cover N logCardM Phi0 cardMmax
      hN_nonneg hcap_nonneg hcardMmax hcap_le hfano
  -- The floor is strictly positive: Φ₀ > 0 and log(cardMmax) > 0.
  have hlog_pos : 0 < Real.log cardMmax := Real.log_pos hcardMmax
  have hfloor_pos : 0 < Phi0 / Real.log cardMmax := div_pos hPhi0 hlog_pos
  exact solving_rate_ceiling_of_floor W Nbar (Phi0 / Real.log cardMmax)
    hW hfloor_pos hfloor

/-! ## 2. The phase boundary (R.352).

The R.352 order parameter is `μ_N − λ_P`. By `R_352_net_rate_sign` the sign of
the order parameter is the sign of `exp((α−γ)t) − λ₀N₀/W₀`; the BOUNDARY is the
locus `μ_N = λ_P`, equivalently `exp((α−γ)t) = λ₀N₀/W₀`, attained at the
crossing time `t* = log(λ₀N₀/W₀)/(α−γ)` (`R_352_transition_time`). -/

/-- **(phase boundary) At the crossing time the order parameter vanishes.**

The R.352 crossing time `t* = log(λ₀N₀/W₀)/(α−γ)` (with `α ≠ γ` and
`λ₀N₀/W₀ > 0`) realises the phase boundary: it solves the boundary equation
`exp((α−γ)t*) = λ₀N₀/W₀` (R.352 `R_352_transition_time`). Combined with the
order-parameter sign law (R.352 `R_352_net_rate_sign`), at `t*` the rates
satisfy `μ_N(t*) ≤ λ_P(t*)` AND `λ_P(t*) ≤ μ_N(t*)` are simultaneously NOT both
strict — i.e. the strict inequality `μ_N > λ_P` FAILS at `t*` (boundary, not
interior of the active phase). We package the boundary as: `μ_N(t*) > λ_P(t*)`
is FALSE, witnessing that `t*` is the phase boundary rather than the active
phase. -/
theorem optimum_at_phase_boundary
    (W0 N0 lam0 α_eff γ : ℝ)
    (h_N0_pos : 0 < N0) (h_lam0_pos : 0 < lam0) (h_W0_pos : 0 < W0)
    (h_ne : α_eff - γ ≠ 0) :
    let tstar := Real.log (lam0 * N0 / W0) / (α_eff - γ)
    ¬ (R352_CivilizationPhase.muN W0 N0 α_eff tstar
        > R352_CivilizationPhase.lamP lam0 γ tstar) := by
  intro tstar
  -- λ₀N₀/W₀ > 0.
  have hpos : 0 < lam0 * N0 / W0 := by positivity
  -- R.352 crossing time: exp((α−γ)t*) = λ₀N₀/W₀, so it is NOT > λ₀N₀/W₀.
  have hcross :
      Real.exp ((α_eff - γ) * tstar) = lam0 * N0 / W0 :=
    R352_CivilizationPhase.R_352_transition_time W0 N0 lam0 α_eff γ hpos h_ne
  -- R.352 order-parameter sign law: μ_N > λ_P ↔ exp((α−γ)t*) > λ₀N₀/W₀.
  have hsign :
      R352_CivilizationPhase.muN W0 N0 α_eff tstar
        > R352_CivilizationPhase.lamP lam0 γ tstar
      ↔ Real.exp ((α_eff - γ) * tstar) > lam0 * N0 / W0 :=
    R352_CivilizationPhase.R_352_net_rate_sign W0 N0 lam0 α_eff γ tstar
      h_N0_pos h_lam0_pos h_W0_pos
  -- At the boundary the strict order-parameter inequality fails.
  rw [hsign, hcross]
  exact lt_irrefl _

/-! ## 3. The optimal education allocation (R.350 ∘ R.62).

In the `|K_A| ≫ |K_H|` limit the KKT corner kills the two knowledge dimensions
(R.350 `R_350_both_knowledge_corners`), the budget collapses to `c_Z + c_κ = C`
(R.350 `R_350_budget_residual`), and the surviving marginals balance — either
abstractly (R.350 `R_350_marginal_balance`) or via the R.62 divide-by-cost
identity (R.62 `R_62_pairwise_marginal_equality`). -/

/-- **(allocation) Optimal education allocation: corner + budget + balance.**

Bundling R.350 and R.62: in the high-coverage limit (`∂E[N]/∂c_K, ∂E[N]/∂c_H ≤ 0`,
multiplier `λ > 0`) with the KKT verdicts on each knowledge dimension, the
optimal allocation
  * kills the knowledge dimensions `c_K* = 0 ∧ c_H* = 0` (R.350 corner);
  * collapses the budget to `c_Z + c_κ = C` (R.350 budget residual);
  * balances the surviving cost-normalised marginals `∂N/∂c_Z = ∂N/∂c_κ`
    (R.350 marginal balance) AND, with unit costs `c_Z' = c_κ' = 1`, the R.62
    divide-by-cost identity `(∂N/∂c_Z)/c_Z' = (∂N/∂c_κ)/c_κ'`. -/
theorem optimal_education_allocation
    (dEN_dcK dEN_dcH lam cK_star cH_star : ℝ)
    (dEN_dcZ dEN_dcκ : ℝ) (cZ cκ C : ℝ)
    (h_mK : dEN_dcK ≤ 0) (h_mH : dEN_dcH ≤ 0) (h_lam_pos : 0 < lam)
    (h_bdK : cK_star = 0 ∨ dEN_dcK = lam)
    (h_bdH : cH_star = 0 ∨ dEN_dcH = lam)
    (h_budget : cK_star + cZ + cH_star + cκ = C)
    (h_stat_Z : dEN_dcZ = lam * 1) (h_stat_κ : dEN_dcκ = lam * 1) :
    -- corner solution
    (cK_star = 0 ∧ cH_star = 0)
    -- budget residual
    ∧ (cZ + cκ = C)
    -- abstract marginal balance (R.350)
    ∧ (dEN_dcZ = dEN_dcκ)
    -- R.62 cost-normalised marginal equality (unit costs)
    ∧ (dEN_dcZ / 1 = dEN_dcκ / 1) := by
  -- R.350 corner: both knowledge dimensions vanish.
  have hcorner : cK_star = 0 ∧ cH_star = 0 :=
    R350_EduOptimalAllocation.R_350_both_knowledge_corners
      dEN_dcK dEN_dcH lam cK_star cH_star h_mK h_mH h_lam_pos h_bdK h_bdH
  refine ⟨hcorner, ?_, ?_, ?_⟩
  · -- R.350 budget residual.
    exact R350_EduOptimalAllocation.R_350_budget_residual
      cK_star cZ cH_star cκ C h_budget hcorner.1 hcorner.2
  · -- R.350 abstract marginal balance.
    exact R350_EduOptimalAllocation.R_350_marginal_balance
      dEN_dcZ dEN_dcκ lam h_stat_Z h_stat_κ
  · -- R.62 divide-by-cost equality with unit costs c_Z' = c_κ' = 1.
    exact KKTMarginalEquality.R_62_pairwise_marginal_equality
      dEN_dcZ dEN_dcκ 1 1 lam one_ne_zero one_ne_zero h_stat_Z h_stat_κ

/-! ## 4. HEADLINE — civilization capability is a collective phase transition;
optimal education allocation sits at the phase boundary under the conserved
coverage floor, which caps the attainable solving rate. -/

/-- **HEADLINE — `civilization_phase_optimal_education`.**

A civilization at the optimal education allocation under the conserved coverage
floor. With:
  * the conserved subdomain-mass coverage mixture of the R6/R5 tower (its
    normalisation `∑ cw = 1` GENERATED by T.18.10 conservation, R6_Agent6
    `cw_sum`), per-subdomain nonnegative counts `N`, per-subdomain R.811 Fano
    accumulations `Φ₀ ≤ N_a·log(cardM_a)`, uniform alphabet ceiling
    `cardMmax > 1`, `Φ₀ > 0`, work budget `W ≥ 0`;
  * the R.352 phase data `W₀, N₀, λ₀, α_eff, γ` (`α_eff ≠ γ`) with the crossing
    time `t* = log(λ₀N₀/W₀)/(α−γ)`;
  * the R.350 KKT allocation data (knowledge marginals `≤ 0`, `λ > 0`, KKT
    verdicts, budget, unit-cost stationarity);
  * a driving civilization activity `act`,
the optimal education allocation satisfies, simultaneously:

  (i)   **normalisation generated by conservation (R6/R5 tower):**
            `∑_a (cw p_X a) = 1`;
  (ii)  **conserved coverage floor (R6_Agent6):**
            `Φ₀ / log(cardMmax) ≤ N̄ := ∑_a (cw p_X a)·N_a`;
  (iii) **solving-rate ceiling (the new cap):**
            `W / N̄ ≤ W / (Φ₀/log(cardMmax))`;
  (iv)  **committee min ≤ conserved average (R5_Agent8):**
            `min_a N_a ≤ N̄`;
  (v)   **optimum at the phase boundary (R.352):**
            `μ_N(t*) > λ_P(t*)` is FALSE — the order parameter vanishes;
  (vi)  **KKT corner + budget residual (R.350):**
            `c_K* = 0 ∧ c_H* = 0` and `c_Z + c_κ = C`;
  (vii) **R.62 cost-normalised marginal balance:**
            `(∂N/∂c_Z)/c_Z' = (∂N/∂c_κ)/c_κ'`;
  (viii)**driving activity classified (R.22):**
            `act` satisfies the N/K/P trichotomy.

So civilization capability IS a collective phase transition; the optimal
education allocation sits at the phase boundary; the conserved coverage floor
caps the attainable solving rate. Chains R6_Agent6 ∘ R5_Agent8 (coverage tower)
∘ R.352 (phase) ∘ R.350 ∘ R.62 (allocation) ∘ R.22 (trichotomy). -/
theorem civilization_phase_optimal_education
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (hne : (Finset.univ :
        Finset (R6_Agent6_FanoFloorFromConservationGenerator.Committee parts)).Nonempty)
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (N logCardM :
        R6_Agent6_FanoFloorFromConservationGenerator.Committee parts → ℝ)
    (W Phi0 cardMmax : ℝ)
    (hW : 0 ≤ W)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hPhi0 : 0 < Phi0)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a)
    -- R.352 phase data
    (W0 N0 lam0 α_eff γ : ℝ)
    (h_N0_pos : 0 < N0) (h_lam0_pos : 0 < lam0) (h_W0_pos : 0 < W0)
    (h_ne : α_eff - γ ≠ 0)
    -- R.350 / R.62 allocation data
    (dEN_dcK dEN_dcH lam cK_star cH_star dEN_dcZ dEN_dcκ cZ cκ C : ℝ)
    (h_mK : dEN_dcK ≤ 0) (h_mH : dEN_dcH ≤ 0) (h_lam_pos : 0 < lam)
    (h_bdK : cK_star = 0 ∨ dEN_dcK = lam)
    (h_bdH : cH_star = 0 ∨ dEN_dcH = lam)
    (h_budget : cK_star + cZ + cH_star + cκ = C)
    (h_stat_Z : dEN_dcZ = lam * 1) (h_stat_κ : dEN_dcκ = lam * 1)
    -- R.22 driving activity
    (act : CivilizationTrichotomy.Activity) :
    let Nbar := ∑ a : R6_Agent6_FanoFloorFromConservationGenerator.Committee parts,
        R6_Agent6_FanoFloorFromConservationGenerator.cw p_X a * N a
    let tstar := Real.log (lam0 * N0 / W0) / (α_eff - γ)
    -- (i) normalisation GENERATED by T.18.10 conservation (R6/R5 tower)
    (∑ a : R6_Agent6_FanoFloorFromConservationGenerator.Committee parts,
        R6_Agent6_FanoFloorFromConservationGenerator.cw p_X a = 1)
    -- (ii) conserved coverage floor (R6_Agent6)
    ∧ (Phi0 / Real.log cardMmax ≤ Nbar)
    -- (iii) solving-rate ceiling (the new cap)
    ∧ (W / Nbar ≤ W / (Phi0 / Real.log cardMmax))
    -- (iv) committee min ≤ conserved average (R5_Agent8)
    ∧ (Finset.univ.inf' hne N ≤ Nbar)
    -- (v) optimum at the phase boundary (R.352): order parameter vanishes
    ∧ (¬ (R352_CivilizationPhase.muN W0 N0 α_eff tstar
          > R352_CivilizationPhase.lamP lam0 γ tstar))
    -- (vi) KKT corner + budget residual (R.350)
    ∧ ((cK_star = 0 ∧ cH_star = 0) ∧ (cZ + cκ = C))
    -- (vii) R.62 cost-normalised marginal balance
    ∧ (dEN_dcZ / 1 = dEN_dcκ / 1)
    -- (viii) driving activity classified by the R.22 trichotomy
    ∧ ((CivilizationTrichotomy.isTypeI act ∨ CivilizationTrichotomy.isTypeII act
          ∨ CivilizationTrichotomy.isTypeIII act)
        ∧ ¬ (CivilizationTrichotomy.isTypeI act ∧ CivilizationTrichotomy.isTypeII act)) := by
  intro Nbar tstar
  -- (i) generator-derived normalisation (R6_Agent6 cw_sum).
  have hi : ∑ a, R6_Agent6_FanoFloorFromConservationGenerator.cw p_X a = 1 :=
    R6_Agent6_FanoFloorFromConservationGenerator.cw_sum
      p_X h_norm parts h_disjoint h_cover
  -- (ii) conserved coverage floor (R6_Agent6).
  have hii : Phi0 / Real.log cardMmax ≤ Nbar :=
    R6_Agent6_FanoFloorFromConservationGenerator.conserved_mixture_fano_floor
      p_X h_norm parts h_disjoint h_cover N logCardM Phi0 cardMmax
      hN_nonneg hcap_nonneg hcardMmax hcap_le hfano
  -- (iii) solving-rate ceiling (a).
  have hiii : W / Nbar ≤ W / (Phi0 / Real.log cardMmax) :=
    collective_solving_rate_ceiling p_X h_norm parts h_disjoint h_cover
      N logCardM W Phi0 cardMmax hW hN_nonneg hcap_nonneg hPhi0 hcardMmax
      hcap_le hfano
  -- (iv) committee min ≤ conserved average (R5_Agent8).
  have hiv : Finset.univ.inf' hne N ≤ Nbar :=
    R5_Agent8_MixtureFanoCoverage.committee_min_le_mixture
      N (R6_Agent6_FanoFloorFromConservationGenerator.cw p_X) hne
      (R6_Agent6_FanoFloorFromConservationGenerator.cw_nonneg
        p_X h_norm parts h_disjoint h_cover)
      hi
  -- (v) optimum at the phase boundary (R.352).
  have hv : ¬ (R352_CivilizationPhase.muN W0 N0 α_eff tstar
          > R352_CivilizationPhase.lamP lam0 γ tstar) :=
    optimum_at_phase_boundary W0 N0 lam0 α_eff γ h_N0_pos h_lam0_pos h_W0_pos h_ne
  -- (vi)+(vii) optimal allocation (R.350 ∘ R.62).
  have halloc := optimal_education_allocation
    dEN_dcK dEN_dcH lam cK_star cH_star dEN_dcZ dEN_dcκ cZ cκ C
    h_mK h_mH h_lam_pos h_bdK h_bdH h_budget h_stat_Z h_stat_κ
  -- (viii) R.22 trichotomy on the driving activity.
  have htri := CivilizationTrichotomy.R_22_trichotomy act
  exact ⟨hi, hii, hiii, hiv, hv, ⟨halloc.1, halloc.2.1⟩, halloc.2.2.2,
    ⟨htri.1, htri.2.1⟩⟩

end R7_Agent10_CivilizationPhaseEducation

end MIP
