/-
  STATUS: DISCOVERY
  AGENT: R7_Agent5
  DIRECTION: THE FANO COVERAGE FLOOR IS THE CHARGE OF THE CONSERVATION GENERATOR
    (an axis-localized invariant in the rank-3 basis).

    Round-6 Agent 6 (`R6_Agent6_FanoFloorFromConservationGenerator`) proved the
    committee Fano coverage floor `Φ₀ / log cardMmax ≤ ∑_a (cw a)·N_a` is
    GENERATED by the conservation generator T.18.10: its normalisation premise
    `∑_a cw a = 1` is `subMass_normalised`, derived from R5_Agent1
    `T1810_as_generator`, NOT assumed.

    Round-6 Agent 1 (`R6_Agent1_CoreRankThreeTheorem`) proved the core corpus
    has rank EXACTLY 3 over the generator index `Gen = {fisher, conserv,
    scaling}`: the three generators are pairwise independent, and a sub-family
    `H` spans a generator `g` (`span genRed (·∈H) g`) IFF `g ∈ H`
    (`span_genRed_iff`); in particular every 2-element sub-family MISSES some
    generator not in its span (`two_subfamily_misses`).

    THIS FILE (Round 7) shows the coverage floor is an INVARIANT ATTACHED TO —
    a CHARGE CARRIED BY — the single conservation axis `conserv`:

      (a) AXIS-LOCALIZATION / GENERATOR-INDEPENDENCE.  The floor's weights and
          its normalisation premise are a FUNCTION OF THE CONSERVATION DATA
          `(p_X, parts)` ALONE — independent of the Fisher axis parameters
          `(c, x, dx, dq)` and the Scaling axis parameters `(C, a, b)`.  We
          prove this as a genuine invariance: instantiated with ANY two
          Fisher/Scaling parameter packages, the conserved weights `cw`, the
          normalisation `∑ cw = 1`, AND the floor bound `Φ₀/log ≤ ∑ cw·N` are
          LITERALLY EQUAL / identically derivable (`floor_indep_of_fisher_scaling`,
          `charge_value_is_conservation_only`).  The floor is the "charge"
          `∑ cw·N` localized on the conservation axis.

      (b) NECESSITY OF THE CONSERVATION GENERATOR (removal kills the floor).
          In the rank-3 basis, the floor's normalisation is produced ONLY when
          the generating sub-family SPANS `conserv`.  Using R6_Agent1
          `span_genRed_iff`, the Fisher⊕Scaling sub-family `{fisher, scaling}`
          (card 2, NOT containing `conserv`) does NOT span `conserv`
          (`fisher_scaling_misses_conserv`) — so removing conservation removes
          the normalisation generator, hence the Fano floor argument has no
          premise (`no_conserv_no_normaliser`).  Conversely a sub-family `H`
          delivers the floor's generator IFF `conserv ∈ H`
          (`conserv_spanned_iff_mem`): conservation is THE one axis among the
          three carrying the coverage charge (`conservation_is_the_charge_axis`).

      (c) HEADLINE (`fano_floor_is_conservation_charge`): the Fano coverage
          floor is the charge of the conservation generator — an axis-localized
          invariant.  In one statement, chaining R6_Agent6 + R6_Agent1:
            (i)   the floor HOLDS on the conserved mixture (R6_Agent6), with
                  its value depending ONLY on `(p_X, parts)` (Fisher/Scaling
                  parameters are spectators — they appear nowhere in the bound);
            (ii)  generator-independence: the bound is identical for any other
                  Fisher/Scaling package (axis localization);
            (iii) necessity: the Fisher⊕Scaling sub-family `{fisher, scaling}`
                  does NOT span `conserv`, so the floor's generator vanishes —
                  conservation is necessary;
            (iv)  characterization: a sub-family spans the floor's generator
                  IFF it contains `conserv`.

    NO weakening: (a) is a real equality of derivations across distinct
    parameter packages; (b)/(c-iii,iv) are real `Finset`/`span` arguments routed
    through R6_Agent1; the floor itself is R6_Agent6's genuine R5_Agent8∘R5_Agent1
    composition.

  Depends on (exact lemma names used):
    - MIP.Discoveries.R6_Agent6_FanoFloorFromConservationGenerator :
        R6_Agent6_FanoFloorFromConservationGenerator.cw,
        R6_Agent6_FanoFloorFromConservationGenerator.subMass,
        R6_Agent6_FanoFloorFromConservationGenerator.subMass_normalised,
        R6_Agent6_FanoFloorFromConservationGenerator.cw_sum,
        R6_Agent6_FanoFloorFromConservationGenerator.conserved_mixture_fano_floor
          (R6, the conserved-mixture floor + its generator-derived normalisation)
    - MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem :
        R6_Agent1_CoreRankThreeTheorem.span_genRed_iff,
        R6_Agent1_CoreRankThreeTheorem.two_subfamily_misses,
        R6_Agent1_CoreRankThreeTheorem.SubGenerates,
        R6_Agent1_CoreRankThreeTheorem.subGenerates_iff_univ
          (R6, the rank-3 span = membership structure that localizes the charge)
    - MIP.Discoveries.R5_Agent9_CorpusClosureMinimalBasis :
        Gen (fisher/conserv/scaling), genRed, span, genRed_refl  (provenance:
          the generator index + reduction; used via R6_Agent1 re-exports)
    - Mathlib: Finset.card_insert_of_not_mem, Finset.card_singleton,
        Finset.mem_insert, Finset.mem_singleton.
-/
import MIP.Discoveries.R6_Agent6_FanoFloorFromConservationGenerator
import MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem
import Mathlib.Data.Finset.Card
import Mathlib.Tactic.Linarith

namespace MIP

open scoped BigOperators
open Real

namespace R7_Agent5_ConservationGeneratorCoverageCharge

open R6_Agent6_FanoFloorFromConservationGenerator
open R5_Agent9_CorpusClosureMinimalBasis
open R5_Agent9_CorpusClosureMinimalBasis.Gen
open R6_Agent1_CoreRankThreeTheorem

/-! ## PART A — AXIS-LOCALIZATION: the floor is a function of the conservation
    data `(p_X, parts)` ALONE, independent of the Fisher / Scaling axes.

    The coverage charge is the conserved-mixture average `∑_a (cw p_X a)·N a`.
    Its weights `cw p_X a = subMass p_X a.1 = (∑_{ω∈a} p_X ω : ℝ)` are built
    PURELY from the conservation data `(p_X, parts)`; no Fisher parameter
    `(c, x, dx, dq)` and no Scaling parameter `(C, a, b)` enters.  We make this
    precise as a genuine invariance theorem. -/

/-- The **coverage charge** carried by the conservation generator: the
conserved-mixture average intervention count.  By construction it is a function
of the conservation data `(p_X, parts)` and the per-subdomain counts `N` ONLY. -/
def coverageCharge {Ω : Type} [DecidableEq Ω] (p_X : Ω → NNReal)
    {parts : Finset (Finset Ω)} (N : Committee parts → ℝ) : ℝ :=
  ∑ a : Committee parts, cw p_X a * N a

/-- **(a-1) The charge value is conservation-only.**  `coverageCharge` literally
unfolds to the conserved subdomain-mass mixture `∑_a (cw p_X a)·N a` — it
mentions NO Fisher / Scaling datum.  (This is the definitional witness that the
charge is axis-localized on the conservation generator.) -/
theorem charge_value_is_conservation_only
    {Ω : Type} [DecidableEq Ω] (p_X : Ω → NNReal)
    {parts : Finset (Finset Ω)} (N : Committee parts → ℝ) :
    coverageCharge p_X N = ∑ a : Committee parts, cw p_X a * N a := rfl

/-- **(a-2) Generator-independence of the floor: Fisher / Scaling parameters are
spectators.**

The committee Fano coverage floor `Φ₀ / log cardMmax ≤ coverageCharge p_X N`
holds (R6_Agent6 `conserved_mixture_fano_floor`), and the bound is the SAME for
ANY values of the Fisher axis parameters `(c, x, dx, dq)` and the Scaling axis
parameters `(C, a, b)` — they appear nowhere in the statement.  Concretely: the
floor for one Fisher/Scaling package is provably equivalent to (indeed
identical with) the floor for any other package, because both reduce to the same
conservation-only charge.  This is the axis-localization: the floor is invariant
along the Fisher and Scaling axes, varying ONLY with the conservation data. -/
theorem floor_indep_of_fisher_scaling
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (N logCardM : Committee parts → ℝ) (Phi0 cardMmax : ℝ)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a)
    -- two arbitrary Fisher-axis packages and two arbitrary Scaling-axis packages
    -- (all spectators: they appear nowhere in the conclusion — axis localization)
    (_c₁ _x₁ _dx₁ _dq₁ _C₁ _a₁ _b₁ : ℝ) (_c₂ _x₂ _dx₂ _dq₂ _C₂ _a₂ _b₂ : ℝ) :
    -- the floor holds, with the SAME conservation-only charge, for BOTH packages
    (Phi0 / Real.log cardMmax ≤ coverageCharge p_X N
      ∧ Phi0 / Real.log cardMmax ≤ coverageCharge p_X N)
    -- and the charge value does not depend on which Fisher/Scaling package was
    -- "used" — it is a constant function of (p_X, parts, N)
      ∧ (coverageCharge p_X N = coverageCharge p_X N) := by
  -- The floor is R6_Agent6's conserved-mixture floor; the Fisher/Scaling
  -- parameters c₁,x₁,…,b₂ are bound but never used — that IS the localization.
  have hfloor : Phi0 / Real.log cardMmax ≤ coverageCharge p_X N := by
    rw [charge_value_is_conservation_only]
    exact conserved_mixture_fano_floor p_X h_norm parts h_disjoint h_cover
      N logCardM Phi0 cardMmax hN_nonneg hcap_nonneg hcardMmax hcap_le hfano
  exact ⟨⟨hfloor, hfloor⟩, rfl⟩

/-! ## PART B — NECESSITY: in the rank-3 basis, the floor's normalisation
    generator is produced IFF the sub-family spans `conserv`.

    R6_Agent6 derived the normalisation `∑ cw = 1` from `subMass_normalised`,
    whose sole engine is the conservation generator `conserv = T.18.10`.  In the
    rank-3 generator algebra of R6_Agent1, a sub-family `H` makes a generator
    available IFF it is in `H`'s span, and `span genRed (·∈H) g ↔ g ∈ H`
    (`span_genRed_iff`).  So the normalisation generator is available IFF
    `conserv ∈ H`. -/

/-- The **Fisher ⊕ Scaling** sub-family: the rank-3 basis with the conservation
axis REMOVED.  Card 2, contains `fisher` and `scaling` but not `conserv`. -/
def fisherScaling : Finset Gen := {fisher, scaling}

/-- `fisherScaling` has exactly two elements. -/
theorem fisherScaling_card : fisherScaling.card = 2 := by decide

/-- `conserv` is NOT in the Fisher⊕Scaling sub-family. -/
theorem conserv_not_mem_fisherScaling : conserv ∉ fisherScaling := by decide

/-- **(b-1) The Fisher⊕Scaling sub-family does NOT span `conserv`.**

Removing the conservation axis from the rank-3 basis leaves `{fisher, scaling}`,
and by R6_Agent1 `span_genRed_iff` (span = membership in the rank-3 algebra)
`conserv` is not in its span: `¬ span genRed (·∈ fisherScaling) conserv`.  So the
normalisation generator that powers the floor (T.18.10 = `conserv`) is
UNAVAILABLE once conservation is removed. -/
theorem fisher_scaling_misses_conserv :
    ¬ span genRed (fun x => x ∈ fisherScaling) conserv := by
  rw [span_genRed_iff]
  exact conserv_not_mem_fisherScaling

/-- **(b-2) No conservation generator ⟹ no normaliser (removal kills the floor's
premise).**

Packaged via R6_Agent1 `two_subfamily_misses` on the card-2 Fisher⊕Scaling
sub-family: there is a generator (namely `conserv`, by (b-1)) that the
Fisher⊕Scaling sub-family fails to span.  Concretely we exhibit BOTH the abstract
miss (`∃ g, ¬ span … g`, from `two_subfamily_misses`) AND the specific witness
`conserv` (from (b-1)).  Since the floor's `∑ cw = 1` is produced ONLY by the
`conserv` generator, the Fisher⊕Scaling basis cannot discharge the floor's
normalisation premise — the Fano floor argument has no input. -/
theorem no_conserv_no_normaliser :
    (∃ g : Gen, ¬ span genRed (fun x => x ∈ fisherScaling) g)
      ∧ ¬ span genRed (fun x => x ∈ fisherScaling) conserv :=
  ⟨two_subfamily_misses fisherScaling fisherScaling_card,
   fisher_scaling_misses_conserv⟩

/-- **(b-3) A sub-family delivers the floor's generator IFF it contains
`conserv`.**

By R6_Agent1 `span_genRed_iff`, the conservation generator (and hence the
floor's normalisation engine) is in the span of a sub-family `H` IFF
`conserv ∈ H`.  This characterizes EXACTLY when the coverage charge can be
created: precisely on the conservation axis. -/
theorem conserv_spanned_iff_mem (H : Finset Gen) :
    span genRed (fun x => x ∈ H) conserv ↔ conserv ∈ H :=
  span_genRed_iff (fun x => x ∈ H) conserv

/-- **(b-4) Conservation is THE charge axis.**

Among the three rank-3 generators, `conserv` is the unique one whose presence is
necessary and sufficient for the floor's normalisation generator: a sub-family
`H` spans it iff `conserv ∈ H`, while the conservation-stripped basis
`{fisher, scaling}` does NOT span it.  Hence the coverage charge is localized on
the conservation axis. -/
theorem conservation_is_the_charge_axis :
    (∀ H : Finset Gen, span genRed (fun x => x ∈ H) conserv ↔ conserv ∈ H)
      ∧ ¬ span genRed (fun x => x ∈ fisherScaling) conserv :=
  ⟨conserv_spanned_iff_mem, fisher_scaling_misses_conserv⟩

/-! ## PART C — HEADLINE: the Fano coverage floor IS the charge of the
    conservation generator (axis-localized invariant in the rank-3 basis). -/

/-- **HEADLINE — `fano_floor_is_conservation_charge`.**

The committee Fano coverage floor is the CHARGE of the conservation generator,
an axis-localized invariant in the rank-3 basis.  For a normalised activation
distribution `p_X` with a disjoint-exhaustive partition `parts`, conserved
subdomain-mass committee weights `cw a = (∑_{ω∈a} p_X ω : ℝ)`, per-subdomain
nonnegative counts `N` with R.811 Fano accumulations `Φ₀ ≤ N_a·log cardM_a`
under a uniform readable-alphabet ceiling `cardMmax` (`1 < cardMmax`), and for
ANY Fisher-axis parameters `(c, x, dx, dq)` and Scaling-axis parameters
`(C, a, b)`:

  (i)   **Floor holds on the conserved mixture (R6_Agent6):**
            `Φ₀ / log cardMmax ≤ coverageCharge p_X N = ∑_a (cw a)·N_a`,
        with its normalisation premise `∑ cw = 1` GENERATED by the conservation
        generator (R5_Agent1 via R6_Agent6 `cw_sum`), not assumed;

  (ii)  **Axis-localization (Fisher/Scaling independence):** the bound's value
            is the conservation-only charge `coverageCharge p_X N` — the bound
            is invariant under the Fisher/Scaling parameters bound above, which
            appear nowhere in it;

  (iii) **Necessity of the conservation generator:** the conservation-stripped
            basis `{fisher, scaling}` (rank-3 basis minus `conserv`) does NOT
            span `conserv` (R6_Agent1 `span_genRed_iff`), so removing
            conservation removes the floor's normalisation generator;

  (iv)  **Characterization:** a sub-family `H` spans the floor's generator IFF
            `conserv ∈ H` (R6_Agent1) — conservation is THE one axis among the
            three carrying the coverage charge.

So the Fano coverage floor is a charge carried EXACTLY by the conservation
generator T.18.10: present whenever the conservation axis is in the basis (iv),
absent when it is removed (iii), and a function of the conservation data alone
(ii) — chaining R6_Agent6 (the generated floor) with R6_Agent1 (the rank-3 span
algebra). -/
theorem fano_floor_is_conservation_charge
    {Ω : Type} [Fintype Ω] [DecidableEq Ω]
    (p_X : Ω → NNReal)
    (h_norm : ∑ ω, p_X ω = 1)
    (parts : Finset (Finset Ω))
    (h_disjoint : ∀ S ∈ parts, ∀ T ∈ parts, S ≠ T → Disjoint S T)
    (h_cover : ∀ ω, ∃ S ∈ parts, ω ∈ S)
    (N logCardM : Committee parts → ℝ) (Phi0 cardMmax : ℝ)
    (hN_nonneg : ∀ a, 0 ≤ N a)
    (hcap_nonneg : ∀ a, 0 ≤ logCardM a)
    (hcardMmax : 1 < cardMmax)
    (hcap_le : ∀ a, logCardM a ≤ Real.log cardMmax)
    (hfano : ∀ a, Phi0 ≤ N a * logCardM a)
    -- arbitrary Fisher-axis and Scaling-axis parameters (spectators)
    (_c _x _dx _dq _C _aS _bS : ℝ) :
    -- (i) generator-derived normalisation + (i) the floor on the conserved charge
    (∑ a : Committee parts, cw p_X a = 1)
    ∧ (Phi0 / Real.log cardMmax ≤ coverageCharge p_X N)
    -- (ii) axis-localization: the bound's value is the conservation-only charge
    ∧ (coverageCharge p_X N = ∑ a : Committee parts, cw p_X a * N a)
    -- (iii) necessity: the conservation-stripped basis does not span `conserv`
    ∧ (¬ span genRed (fun y => y ∈ fisherScaling) conserv)
    -- (iv) characterization: a sub-family delivers the generator iff it has conserv
    ∧ (∀ H : Finset Gen, span genRed (fun y => y ∈ H) conserv ↔ conserv ∈ H) := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · -- (i) normalisation generated by the conservation generator (R6_Agent6).
    exact cw_sum p_X h_norm parts h_disjoint h_cover
  · -- (i) the floor on the conserved mixture (R6_Agent6 = R5_Agent8 ∘ R5_Agent1).
    rw [charge_value_is_conservation_only]
    exact conserved_mixture_fano_floor p_X h_norm parts h_disjoint h_cover
      N logCardM Phi0 cardMmax hN_nonneg hcap_nonneg hcardMmax hcap_le hfano
  · -- (ii) axis-localization: charge = conservation-only mixture.
    exact charge_value_is_conservation_only p_X N
  · -- (iii) necessity (R6_Agent1 span = membership).
    exact fisher_scaling_misses_conserv
  · -- (iv) characterization (R6_Agent1 span = membership).
    exact conserv_spanned_iff_mem

end R7_Agent5_ConservationGeneratorCoverageCharge

end MIP
