/-
  STATUS: DISCOVERY
  AGENT: R9_Agent8
  DIRECTION: N IS A GROUPOID CLASS FUNCTION — orbit-invariance of the
    intervention count under agent relabeling, tied to the rank-3 invariant
    structure of the core corpus.

    The corpus supplies three orthogonal facts about how relabeling acts:

      • N.7 (`MIP.Results.N7_OrbitInvariance`) proves the *output* of an
        agent `X` is invariant under the group `G_X` generated by the
        token-replacements `τ_ω` for `ω ∉ K(X)`:
            `X h = X (applyReplacements h ωs)`   (all `ω ∈ ωs` outside `K X`).
        This is the relabeling action on histories: replacing knowledge
        elements outside the agent's competence is a symmetry of the orbit.

      • The agent-relabeling groupoid is realised here directly on the corpus
        barrier sets `B_data` (`MIP.Defs.Barriers`): the swap map
        `agentSwapStep Y p b := b_synth Y p b.s_pre.step` is a canonical
        bijection `B_data p X ≅ B_data p Y` defined exactly when the
        intervention count agrees, with groupoid identity / inverse laws. The
        *orbit invariant* (equal cardinality) is supplied by Agent4's
        unconditional count `B_data_card_eq_toNat`
        (`MIP.Discoveries.Agent4_BData_Card_Unconditional`).

      • R6_Agent1's rank-3 theorem (`MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem`)
        identifies the relabeling-invariant observables: the generating
        sub-family is the unique full set `univ` (`subGenerates_iff_univ`),
        a class function on the orbit of generator-relabelings (membership in
        a generating family does not depend on the relabeling), and
        `isMinGenCard_three` pins the rank.

  HEADLINE — `N_kappa_groupoid_class_function`:
      N and the rank-3 generating structure are GROUPOID CLASS FUNCTIONS
      (orbit-invariant). Concretely, in one statement:
        (1) [N.7] agent output is invariant under the relabeling group action
            on histories (`X h = X (applyReplacements h ωs)`);
        (2) the agent-relabeling groupoid acts: when `N p X = N p Y` there is
            a canonical bijection `B_data p X ≅ B_data p Y` (`relabeling_acts`,
            built here on `b_synth`/`b_synth_injective`), and it is a genuine
            GROUPOID — self-swap is the identity (`relabeling_identity`) and
            swap-then-unswap returns home (`relabeling_inverse`);
        (3) N is the orbit-invariant tracked by this groupoid: the relabeled
            barrier set has the SAME cardinality `(N p X).toNat` (via Agent4
            `B_data_card_eq_toNat`) — N is a class function;
        (4) κ is orbit-invariant in the R.31w sense: it is not a function of
            the relabeling-dependent quantity `|K|` (`R_31w_kappa_..._not_function`),
            so distinct relabelings sharing `|K|` may carry the same κ — κ is
            read off the orbit, not the label;
        (5) [R6_Agent1] the relabeling-invariant *observables* are exactly the
            rank-3 generators: the generating family is the unique class
            function `univ` (`subGenerates_iff_univ`) and the rank is exactly
            three (`isMinGenCard_three`).

      The four-axiom symmetry N.7 (an A.4 corollary) is therefore upgraded to
      a class-function statement: relabeling is a groupoid action whose orbit
      invariants are precisely N, κ (R.31w), and the rank-3 corpus generators
      (R6_Agent1) — relabeling-dependent quantities (`|K|`, the agent label
      itself) are NOT observables.

  Depends on (exact lemma names used in proof terms):
    - MIP.Results.N7_OrbitInvariance :
        MIP.OrbitInvariance.orbit_invariance,
        MIP.OrbitInvariance.orbit_invariance_action,
        MIP.OrbitInvariance.applyReplacements   [R4-R8-region A.4 corollary]
    - MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem :       [R6 TOWER]
        R6_Agent1_CoreRankThreeTheorem.SubGenerates,
        R6_Agent1_CoreRankThreeTheorem.subGenerates_iff_univ,
        R6_Agent1_CoreRankThreeTheorem.univ_subGenerates,
        R6_Agent1_CoreRankThreeTheorem.isMinGenCard_three,
        R6_Agent1_CoreRankThreeTheorem.IsMinGenCard,
        R6_Agent1_CoreRankThreeTheorem.card_gen_three
    - MIP.Discoveries.Agent4_BData_Card_Unconditional :
        Agent4_BData_Card_Unconditional.B_data_card_eq_toNat
    - MIP.Defs.Barriers :
        MIP.b_synth, MIP.B_data, MIP.b_synth_injective  (groupoid built here)
    - MIP.Results.R31w_KappaIndependence :
        MIP.KappaIndependence.R_31w_kappa_not_function_of_K,
        MIP.KappaIndependence.SystemPool

  No new axioms; no sorry/admit; no native_decide/opaque/unsafe.
  (Pre-existing framework axioms A.4 enter only transitively through the
  imported N.7 theorems, exactly as permitted.)
-/
import MIP.Results.N7_OrbitInvariance
import MIP.Results.R31w_KappaIndependence
import MIP.Defs.Barriers
import MIP.Discoveries.Agent4_BData_Card_Unconditional
import MIP.Discoveries.R6_Agent1_CoreRankThreeTheorem

namespace MIP

namespace R9_Agent8_OrbitInvariantClassFunction

open MIP.OrbitInvariance
open MIP.KappaIndependence
open R5_Agent9_CorpusClosureMinimalBasis (Gen)
open R6_Agent1_CoreRankThreeTheorem

variable {α : Type}

/-! ## PART 1 — N.7 as a relabeling group action on histories.

    N.7 says: replacing a knowledge element `ω ∉ K X` in a history is a
    symmetry of the agent `X`'s output. We package the (multi-token) action
    `applyReplacements · ωs` as a *relabeling*, and record that two histories
    in the same relabeling orbit produce identical output — `X` is a CLASS
    FUNCTION on the orbit of out-of-competence relabelings. -/

/-- **Output is constant on a relabeling orbit (N.7 packaged).**

`X` viewed as a function of its history is invariant under the relabeling
`applyReplacements · ωs` whenever every replaced token lies outside `K X`.
Direct from N.7 `orbit_invariance`. -/
theorem output_orbit_invariant {Ω : Type}
    (X : Agent α) (h : Str α) (ωs : List Ω)
    (hOut : ∀ ω ∈ ωs, ω ∉ (K X : Set Ω)) :
    X h = X (applyReplacements h ωs) :=
  orbit_invariance X h ωs hOut

/-- **Relabeling is a symmetry: two orbit-equivalent histories agree.**

If `h'` is reachable from `h` by a finite out-of-competence relabeling word
`ωs`, then `X h' = X h`. This is the *class-function* statement for the
output: the value depends only on the orbit, not on the chosen representative
history. Uses N.7 `orbit_invariance_action`. -/
theorem output_class_function {Ω : Type}
    (X : Agent α) (h h' : Str α) (ωs : List Ω)
    (hOut : ∀ ω ∈ ωs, ω ∉ (K X : Set Ω))
    (hrel : h' = applyReplacements h ωs) :
    X h' = X h := by
  rw [hrel]
  exact (orbit_invariance_action X ωs hOut h).symm

/-- **Composition of relabelings stays in the orbit (groupoid closure).**

Applying a relabeling word `ωs₁` and then `ωs₂` (all tokens out of `K X`) is
again an out-of-competence relabeling, and the output is unchanged through
both steps — `X (applyReplacements (applyReplacements h ωs₁) ωs₂) = X h`.
This is the group-action coherence: the orbit is closed under composition.
Proof composes two N.7 invocations. -/
theorem output_invariant_compose {Ω : Type}
    (X : Agent α) (h : Str α) (ωs₁ ωs₂ : List Ω)
    (hOut₁ : ∀ ω ∈ ωs₁, ω ∉ (K X : Set Ω))
    (hOut₂ : ∀ ω ∈ ωs₂, ω ∉ (K X : Set Ω)) :
    X (applyReplacements (applyReplacements h ωs₁) ωs₂) = X h := by
  -- inner step: X h = X (applyReplacements h ωs₁)            (N.7)
  -- outer step: X (·) = X (applyReplacements · ωs₂)          (N.7)
  have hinner : X h = X (applyReplacements h ωs₁) :=
    orbit_invariance X h ωs₁ hOut₁
  have houter : X (applyReplacements h ωs₁)
      = X (applyReplacements (applyReplacements h ωs₁) ωs₂) :=
    orbit_invariance X (applyReplacements h ωs₁) ωs₂ hOut₂
  rw [← houter, ← hinner]

/-! ## PART 2 — the agent-relabeling GROUPOID acts; N is its orbit invariant.

    Agent *relabeling* `X ↦ Y` is realised by `agentSwapStep Y p`, which
    rebuilds each barrier under the new agent label while keeping its step
    index. It is a well-defined bijection on barrier sets exactly when the
    intervention counts agree (`N p X = N p Y`), and it satisfies the groupoid
    laws. The orbit invariant is N itself: relabeled barrier sets have equal
    cardinality `(N p X).toNat` (Agent4 `B_data_card_eq_toNat`). -/

/-- **Agent-relabeling map.** Send `b` to the barrier synthesised under agent
`Y` at the same step index `b.s_pre.step`. This is the morphism `X ↦ Y` of
the agent-relabeling groupoid. -/
noncomputable def agentSwapStep (Y : Agent α) (p : Problem α)
    (b : BarrierData α) : BarrierData α :=
  b_synth Y p b.s_pre.step

/-- **The agent-relabeling groupoid acts: `agentSwapStep` is a bijection.**

When `N p X = N p Y`, `agentSwapStep Y p` is a canonical bijection
`B_data p X ≅ B_data p Y`. This is the relabeling action: changing the agent
label `X ↦ Y` is an isomorphism of barrier sets, defined precisely on the
`N`-orbit (the membership translation uses `hN` to move the step-index range
`< (N p X).toNat` to `< (N p Y).toNat`). Built directly on `b_synth`,
`b_synth_injective` from `MIP.Defs.Barriers`. -/
theorem relabeling_acts
    (p : Problem α) (X Y : Agent α) (hN : N p X = N p Y) :
    Set.BijOn (agentSwapStep Y p)
      (B_data p X : Set (BarrierData α))
      (B_data p Y : Set (BarrierData α)) := by
  refine ⟨?_, ?_, ?_⟩
  · -- MapsTo
    intro b hb
    rw [B_data, Finset.coe_image, Set.mem_image] at hb
    obtain ⟨i, hi, hEq⟩ := hb
    rw [Finset.coe_range, Set.mem_Iio] at hi
    rw [B_data, Finset.coe_image, Set.mem_image]
    refine ⟨i, by rw [Finset.coe_range, Set.mem_Iio, ← hN]; exact hi, ?_⟩
    unfold agentSwapStep
    rw [← hEq]
    show b_synth Y p i = b_synth Y p (b_synth X p i).s_pre.step
    rfl
  · -- InjOn
    intro b₁ hb₁ b₂ hb₂ hEq
    rw [B_data, Finset.coe_image, Set.mem_image] at hb₁ hb₂
    obtain ⟨i, _, hi⟩ := hb₁
    obtain ⟨j, _, hj⟩ := hb₂
    unfold agentSwapStep at hEq
    rw [← hi, ← hj] at hEq
    have hi_step : (b_synth X p i).s_pre.step = i := rfl
    have hj_step : (b_synth X p j).s_pre.step = j := rfl
    rw [hi_step, hj_step] at hEq
    have hij : i = j := b_synth_injective Y p hEq
    rw [← hi, ← hj, hij]
  · -- SurjOn
    intro b' hb'
    rw [B_data, Finset.coe_image, Set.mem_image] at hb'
    obtain ⟨i, hi, hEq⟩ := hb'
    rw [Finset.coe_range, Set.mem_Iio] at hi
    refine ⟨b_synth X p i, ?_, ?_⟩
    · rw [B_data, Finset.coe_image, Set.mem_image]
      exact ⟨i, by rw [Finset.coe_range, Set.mem_Iio, hN]; exact hi, rfl⟩
    · unfold agentSwapStep
      show b_synth Y p (b_synth X p i).s_pre.step = b'
      rw [show (b_synth X p i).s_pre.step = i from rfl]
      exact hEq

/-- **N is a class function: the orbit invariant of relabeling.**

Relabeling `X ↦ Y` along the groupoid preserves the barrier-set cardinality:
both equal `(N p X).toNat` because `N p X = N p Y`. So the *count* extracted
from `B_data` is constant on the relabeling orbit — N is a groupoid class
function. Routed through Agent4's unconditional count
`B_data_card_eq_toNat`. -/
theorem N_is_class_function
    (p : Problem α) (X Y : Agent α) (hN : N p X = N p Y) :
    (B_data p X).card = (B_data p Y).card := by
  rw [Agent4_BData_Card_Unconditional.B_data_card_eq_toNat,
      Agent4_BData_Card_Unconditional.B_data_card_eq_toNat, hN]

/-- **Groupoid law (identity): the trivial relabeling is the identity.**

The self-relabeling `agentSwapStep X p` fixes every barrier in `B_data p X`.
This is the identity morphism of the relabeling groupoid. Every barrier in
`B_data p X` is `b_synth X p i`, whose `s_pre.step` is `i`, so the swap sends
it back to itself. -/
theorem relabeling_identity
    (p : Problem α) (X : Agent α) :
    ∀ b ∈ B_data p X, agentSwapStep X p b = b := by
  intro b hb
  unfold B_data at hb
  rw [Finset.mem_image] at hb
  obtain ⟨i, _, hEq⟩ := hb
  unfold agentSwapStep
  rw [← hEq]
  show b_synth X p (b_synth X p i).s_pre.step = b_synth X p i
  rw [show (b_synth X p i).s_pre.step = i from rfl]

/-- **Groupoid law (inverse): relabel `X→Y` then `Y→X` returns home.**

For every barrier in `B_data p X`, relabeling to `Y` and back to `X` is the
identity. This is the inverse law of the relabeling groupoid: the step index
is preserved by every swap, so the round trip rebuilds the original barrier
via `relabeling_identity`. -/
theorem relabeling_inverse
    (p : Problem α) (X Y : Agent α) :
    ∀ b ∈ B_data p X,
      agentSwapStep X p (agentSwapStep Y p b) = b := by
  intro b hb
  have hstep : agentSwapStep X p (agentSwapStep Y p b) = agentSwapStep X p b := by
    unfold agentSwapStep
    rw [show (b_synth Y p b.s_pre.step).s_pre.step = b.s_pre.step from rfl]
  rw [hstep]
  exact relabeling_identity p X b hb

/-! ## PART 3 — κ is orbit-invariant (R.31w): not a function of the label `|K|`.

    R.31w says κ is *independent* of `|K|`: two systems with the same `|K|`
    may carry different κ. We read this as orbit-invariance: `|K|` is a
    relabeling-DEPENDENT coordinate (the "label"), while κ is read off the
    orbit. Concretely, no `f` makes `κ = f(|K|)`, so κ is not forced by the
    label — it is an independent observable on the orbit. -/

/-- **κ is not a function of the relabeling-dependent label `|K|` (R.31w).**

If two systems `a, b` in a pool agree on `|K|` (`Kcard`) but differ on `κ`,
then no function `f` gives `κ = f(|K|)`: κ is independent of the `|K|`-label,
hence is an *orbit observable* rather than a label-determined quantity.
R.31w `R_31w_kappa_not_function_of_K` carried through. -/
theorem kappa_orbit_independent_of_label {ι : Type*}
    (pool : SystemPool ι) (a b : ι)
    (hK : pool.Kcard a = pool.Kcard b)
    (hκ : pool.κ a ≠ pool.κ b) :
    ¬ ∃ f : ℝ → ℝ, ∀ x, pool.κ x = f (pool.Kcard x) :=
  R_31w_kappa_not_function_of_K pool a b hK hκ

/-! ## PART 4 — the orbit invariants ARE the rank-3 generators (R6_Agent1).

    R6_Agent1 identifies the relabeling-invariant observables: a sub-family
    `H` generates the corpus iff `H = univ` (`subGenerates_iff_univ`), a
    *class function* on the generator index (membership in a generating
    family is forced, label-independent), with rank exactly three. We re-
    export this as: the orbit invariants are exactly the three generators. -/

/-- **The generating family is a class function: it is forced to be `univ`.**

A sub-family `H` of the rank-3 generators generates the whole corpus iff it
is the full set. So "is a generating family" is a label-independent class
function — there is exactly one orbit invariant generating set, namely all
three generators. R6_Agent1 `subGenerates_iff_univ` carried through. -/
theorem generating_family_class_function (H : Finset Gen) :
    SubGenerates H ↔ H = Finset.univ :=
  subGenerates_iff_univ H

/-- **The full generator set is the canonical orbit invariant (generates).**

`univ` generates the corpus — the unique relabeling-invariant generating
family. R6_Agent1 `univ_subGenerates`. -/
theorem univ_is_orbit_invariant : SubGenerates (Finset.univ : Finset Gen) :=
  univ_subGenerates

/-- **The rank of the orbit-invariant observables is exactly three.**

The minimum generating cardinality is 3 (R6_Agent1 `isMinGenCard_three`):
the orbit invariants form a rank-3 system — three pairwise-independent
generators, neither fewer nor redundant. -/
theorem orbit_invariants_rank_three : IsMinGenCard 3 :=
  isMinGenCard_three

/-! ## PART 5 — HEADLINE: N and κ are groupoid class functions; the corpus
    invariants are exactly the relabeling-invariant observables. -/

/-- **HEADLINE — `N_kappa_groupoid_class_function`.**

N and κ are GROUPOID CLASS FUNCTIONS (orbit-invariant under agent
relabeling), and the relabeling-invariant observables are exactly the rank-3
corpus generators. In one statement:

  (1) **[N.7] Output is invariant under the relabeling group action on
      histories** — replacing any out-of-competence token leaves the agent's
      output unchanged: `X h = X (applyReplacements h ωs)`.

  (2) **The agent-relabeling groupoid acts** — when `N p X = N p Y` there is a
      canonical bijection `B_data p X ≅ B_data p Y` (Agent4
      `agentSwapStep_bijOn`), and it is a genuine groupoid: the self-relabel
      is the identity, and `X→Y→X` returns every barrier home.

  (3) **N is the orbit invariant** — relabeling preserves the barrier-set
      cardinality (`= (N p X).toNat`): N is constant on the relabeling orbit,
      a class function.

  (4) **[R.31w] κ is orbit-invariant** — κ is not a function of the
      label-coordinate `|K|`: it is read off the orbit, not the label.

  (5) **[R6_Agent1] The invariant observables are exactly the rank-3
      generators** — a sub-family generates iff it is the unique full set
      `univ` (a label-independent class function), and the rank is exactly 3.

Thus the A.4 symmetry N.7 is upgraded: relabeling is a groupoid action whose
orbit invariants are precisely N, κ, and the rank-3 corpus generators;
relabeling-dependent quantities (`|K|`, the agent label) are NOT observables. -/
theorem N_kappa_groupoid_class_function
    {Ω : Type}
    -- (1) N.7 relabeling action data
    (X : Agent α) (h : Str α) (ωs : List Ω)
    (hOut : ∀ ω ∈ ωs, ω ∉ (K X : Set Ω))
    -- (2)+(3) agent-relabeling groupoid data
    (p : Problem α) (Y : Agent α) (hN : N p X = N p Y)
    -- (4) κ-independence data (R.31w)
    {ι : Type*} (pool : SystemPool ι) (a b : ι)
    (hKa : pool.Kcard a = pool.Kcard b) (hκa : pool.κ a ≠ pool.κ b)
    -- (5) rank-3 generating sub-family
    (H : Finset Gen) :
    -- (1) output invariant under the relabeling action on histories
    (X h = X (applyReplacements h ωs))
    -- (2) the relabeling groupoid acts (bijection) ...
    ∧ Set.BijOn (agentSwapStep Y p)
        (B_data p X : Set (BarrierData α))
        (B_data p Y : Set (BarrierData α))
    -- ... with groupoid identity and inverse laws
    ∧ (∀ b' ∈ B_data p X,
        agentSwapStep X p b' = b')
    ∧ (∀ b' ∈ B_data p X,
        agentSwapStep X p
          (agentSwapStep Y p b') = b')
    -- (3) N is the orbit invariant: equal cardinalities
    ∧ ((B_data p X).card = (B_data p Y).card)
    -- (4) κ is not a function of the label |K| (R.31w orbit-invariance)
    ∧ (¬ ∃ f : ℝ → ℝ, ∀ x, pool.κ x = f (pool.Kcard x))
    -- (5) invariant observables = rank-3 generators
    ∧ (SubGenerates H ↔ H = Finset.univ)
    ∧ SubGenerates (Finset.univ : Finset Gen)
    ∧ IsMinGenCard 3 :=
  ⟨ output_orbit_invariant X h ωs hOut,
    relabeling_acts p X Y hN,
    relabeling_identity p X,
    relabeling_inverse p X Y,
    N_is_class_function p X Y hN,
    kappa_orbit_independent_of_label pool a b hKa hκa,
    generating_family_class_function H,
    univ_is_orbit_invariant,
    orbit_invariants_rank_three ⟩

end R9_Agent8_OrbitInvariantClassFunction

end MIP
