"""
Direction B (analytic): For each non-chordal DL on S_{1,2} (with an induced
4-cycle β_1β_2β_3β_4), explicitly identify the canonical filler σ_α
(level k-2, disjoint from α), and:

  1. Verify directly that i(σ_α, β_i) ≤ 1 for each i.
  2. Try to identify σ_α as a Hatcher surgery output: search for
     a Dehn-multitwist h ∈ MCG generated by {T_{γ_0}^{±1}, T_α^{±1},
     and small twists of nearby curves} such that h(α) or h(γ_0) = σ_α.
  3. Measure how the i(σ_α, β_i) bound decomposes:
        i(σ_α, β_i)  vs  i(α, β_i)  vs  i(γ_0, β_i)
     and check the empirical inequality
        i(σ_α, β_i) ≤ i(α, β_i) + i(γ_0, β_i)?
     (a weaker, more permissive bound)
  4. Look for the geometric pattern:
        when is the bound TIGHT (= 1)?
        when is it SLACK (= 0)?
     Are the slack cases the ones where bigons cancel?
"""
import curver, json, networkx as nx
from collections import defaultdict, Counter
from itertools import combinations

DATA_PATH = '/mnt/c/Users/12729/Desktop/Math/workspace/projects/op1_geometry/data_S_1_2.json'

S = curver.load(1, 2)
gamma0 = S.curves['a_0']
data = json.load(open(DATA_PATH))
hashes = [tuple(h) for h in data['curves']]
curves = [S.lamination(list(h)) for h in hashes]
f_vals = [gamma0.intersection(c) for c in curves]
levels = defaultdict(list)
for i, v in enumerate(f_vals): levels[v].append(i)

adj = defaultdict(set); edge_iv = {}
for i, j in data['i0_edges']:
    adj[i].add(j); adj[j].add(i); edge_iv[frozenset((i,j))] = 0
for i, j in data['i1_edges']:
    adj[i].add(j); adj[j].add(i); edge_iv[frozenset((i,j))] = 1

def i_query(a, b):
    if a == b: return 0
    key = frozenset((a, b))
    if key in edge_iv: return edge_iv[key]
    return curves[a].intersection(curves[b])

def build_dl_graph(alpha_idx, k):
    DL = sorted([b for b in adj[alpha_idx] if f_vals[b] is not None and f_vals[b] < k])
    G = nx.Graph(); G.add_nodes_from(DL)
    for i, b1 in enumerate(DL):
        for b2 in DL[i+1:]:
            if i_query(b1, b2) <= 1:
                G.add_edge(b1, b2)
    return G, DL

def find_induced_4cycles(G):
    found = []
    nodes = list(G.nodes())
    for combo in combinations(nodes, 4):
        for perm in [(combo[1], combo[2], combo[3]),
                     (combo[1], combo[3], combo[2]),
                     (combo[2], combo[1], combo[3])]:
            o = (combo[0],) + perm
            edges_ok = (G.has_edge(o[0], o[1]) and G.has_edge(o[1], o[2]) and
                        G.has_edge(o[2], o[3]) and G.has_edge(o[3], o[0]))
            if not edges_ok: continue
            chord_ok = (not G.has_edge(o[0], o[2])) and (not G.has_edge(o[1], o[3]))
            if chord_ok:
                found.append(o); break
    return found


# Find non-chordal DLs (with induced 4-cycles)
print("Direction B: bigon-counting decomposition for non-chordal DLs on S_{1,2}.")
print("=" * 78)

non_chordal_data = []
for k_alpha in (4, 5, 6, 7, 8):
    if k_alpha not in levels: continue
    for alpha_idx in levels[k_alpha]:
        G, DL = build_dl_graph(alpha_idx, k_alpha)
        cycles = find_induced_4cycles(G)
        if not cycles: continue
        for cyc in cycles:
            common_nbrs = set(G.neighbors(cyc[0]))
            for v in cyc[1:]:
                common_nbrs &= set(G.neighbors(v))
            common_nbrs -= set(cyc)
            target_fillers = [v for v in common_nbrs if f_vals[v] == k_alpha - 2]
            disjoint_target_fillers = [v for v in target_fillers if i_query(alpha_idx, v) == 0]
            if disjoint_target_fillers:
                # Take the canonical filler (first one)
                sigma = disjoint_target_fillers[0]
                non_chordal_data.append({
                    'alpha': alpha_idx, 'k': k_alpha, 'cycle': cyc,
                    'sigma': sigma,
                    'all_disjoint_target_fillers': disjoint_target_fillers,
                })

print(f"\nNon-chordal (α, 4-cycle) records with canonical σ_α: {len(non_chordal_data)}")

# Per-record: print bigon decomposition
print("\nFor each (α, 4-cycle), measure i(σ_α, β_i) and the bigon decomposition:")
print()
header = f"{'α':>4} {'k':>2} {'σ':>5} {'β':>5} {'iα':>4} {'iγ0':>4} {'i(σ,β)':>7} {'iα+iγ0':>7} "
print(header)
print("-" * len(header))

bound_hits = Counter()
slack_pattern = Counter()
all_within_one = True

for rec in non_chordal_data:
    sigma = rec['sigma']; alpha = rec['alpha']
    iα_σ = i_query(alpha, sigma)
    fσ = f_vals[sigma]
    for β in rec['cycle']:
        iα_β = i_query(alpha, β)
        iγ0_β = f_vals[β]
        iσ_β = i_query(sigma, β)
        # Direct bound from triangle ineq for surgery: should always be ≤ iα_β + iγ0_β
        sum_bound = iα_β + iγ0_β
        within = iσ_β <= 1
        all_within_one = all_within_one and within
        bound_hits[(iα_β, iσ_β)] += 1
        if iσ_β <= 1:
            if iα_β == 0:
                slack_pattern['iα=0_iσ_eq_iσβ'] += 1
            else:
                slack_pattern['iα=1'] += 1
        # Print only first few rows per record + flag interesting
        # (limit output)

# Print first 15 rows
counter = 0
for rec in non_chordal_data:
    if counter > 14: break
    sigma = rec['sigma']; alpha = rec['alpha']
    for β in rec['cycle']:
        iα_β = i_query(alpha, β)
        iγ0_β = f_vals[β]
        iσ_β = i_query(sigma, β)
        sum_bound = iα_β + iγ0_β
        flag = "" if iσ_β <= 1 else "  <<< W4 violated!"
        print(f"{alpha:>4} {rec['k']:>2} {sigma:>5} {β:>5} {iα_β:>4} {iγ0_β:>4} {iσ_β:>7} {sum_bound:>7} {flag}")
        counter += 1
        if counter > 14: break

print()
print(f"All i(σ_α, β_i) ≤ 1: {all_within_one}")
print(f"\n(iα_β, iσ_β) co-occurrence:")
for (a, s), c in sorted(bound_hits.items()):
    print(f"  iα={a}, iσ={s}: {c} cases")

# Hypothesis test: does i(σ, β) = i(α, β)?  (i.e., is σ "equivalent" to α
# from β's perspective?)
match_count = sum(1 for (a, s), c in bound_hits.items() if a == s for _ in range(c))
print(f"\nNumber of (α, β) records where i(σ,β) = i(α,β): {match_count}")

# Specifically when iα = 1 and iσ = 0: this means surgery REMOVED an
# intersection that α had with β. Surprising — would violate the simple
# bound i(σ,β) ≤ i(α,β) + small.
removed = sum(c for (a, s), c in bound_hits.items() if a == 1 and s == 0)
added = sum(c for (a, s), c in bound_hits.items() if a == 0 and s == 1)
print(f"\nintersection REMOVED by surgery (iα=1, iσ=0): {removed}")
print(f"intersection ADDED by surgery (iα=0, iσ=1): {added}")
print(f"intersection PRESERVED (iα=iσ=0): "
      f"{sum(c for (a, s), c in bound_hits.items() if a == 0 and s == 0)}")
print(f"intersection PRESERVED (iα=iσ=1): "
      f"{sum(c for (a, s), c in bound_hits.items() if a == 1 and s == 1)}")
